export const adultStars = [
  // Adult Film Stars & Personalities
  { word: 'Mia Khalifa', clue: 'Former Adult Star Sports Commentator' },
  { word: 'Riley Reid', clue: 'Award Winning Adult Performer' },
  { word: 'Lana Rhoades', clue: 'Adult Star Turned Podcaster' },
  { word: 'Mia Malkova', clue: 'Adult Actress Twitch Streamer' },
  { word: 'Abella Danger', clue: 'Award Winning Adult Film Star' },
  { word: 'Angela White', clue: 'Australian Adult Film Director' },
  { word: 'Adriana Chechik', clue: 'Adult Star Gamer' },
  { word: 'Brandi Love', clue: 'MILF Category Icon' },
  { word: 'Lisa Ann', clue: 'Adult Star Sports Radio Host' },
  { word: 'Asa Akira', clue: 'Adult Actress Author' },
  { word: 'Kendra Lust', clue: 'Adult Film Star Director' },
  { word: 'Nicole Aniston', clue: 'Adult Film Actress Model' },
  { word: 'Phoenix Marie', clue: 'Blonde Adult Film Star' },
  { word: 'Alexis Texas', clue: 'Texas Born Adult Star' },
  { word: 'Piper Perri', clue: 'Petite Adult Actress' },
  { word: 'Elsa Jean', clue: 'Blonde Adult Film Performer' },
  { word: 'Dani Daniels', clue: 'Adult Star Artist' },
  { word: 'Madison Ivy', clue: 'German Born Adult Actress' },
  { word: 'Tori Black', clue: 'Award Winning Adult Performer' },
  { word: 'Jenna Jameson', clue: 'Legendary Adult Film Icon' },
  { word: 'Sasha Grey', clue: 'Adult Star Mainstream Actress' },
  { word: 'Sunny Leone', clue: 'Adult Star Bollywood Actress' },
  { word: 'Stormy Daniels', clue: 'Adult Star Political Figure' },
  { word: 'Ron Jeremy', clue: 'Male Adult Film Legend' },
  { word: 'Johnny Sins', clue: 'Bald Adult Actor Meme' },
  { word: 'James Deen', clue: 'Male Adult Film Star' },
  { word: 'Manuel Ferrara', clue: 'French Male Adult Star' },
  { word: 'Rocco Siffredi', clue: 'Italian Adult Film Legend' },
  { word: 'Riley Steele', clue: 'Digital Playground Contract Star' },
  { word: 'Gianna Michaels', clue: 'Busty Adult Film Star' },
  { word: 'Sara Jay', clue: 'Veteran Adult Actress' },
  { word: 'Kagney Linn Karter', clue: 'Adult Star Exotic Dancer' },
  { word: 'Christy Mack', clue: 'Tattooed Adult Model' },
  { word: 'Bonnie Rotten', clue: 'Heavily Tattooed Adult Star' },
  { word: 'Skin Diamond', clue: 'Alternative Adult Performer' },
  { word: 'Stoya', clue: 'Adult Star Writer' },
  { word: 'Kayden Kross', clue: 'Adult Director Writer' },
  { word: 'Jesse Jane', clue: 'Digital Playground Icon' },
  { word: 'Bree Olson', clue: 'Charlie Sheen Girlfriend' },
  { word: 'Teanna Trump', clue: 'Award Winning Adult Actress' },
  { word: 'Janice Griffith', clue: 'Petite Adult Film Star' },
  { word: 'Karlee Grey', clue: 'Natural Adult Actress' },
  { word: 'Autumn Falls', clue: 'Young Adult Film Star' },
  { word: 'Gabbie Carter', clue: 'Natural Busty Adult Star' },
  { word: 'Lena Paul', clue: 'Curvy Adult Film Actress' },
  { word: 'Skylar Vox', clue: 'Busty Young Adult Star' },
  { word: 'Blake Blossom', clue: 'Blonde Adult Film Performer' },
  { word: 'Emily Willis', clue: 'Award Winning Young Star' },
  { word: 'Natasha Nice', clue: 'French American Adult Star' },
  { word: 'Valentina Nappi', clue: 'Italian Adult Actress' },
  { word: 'Eva Lovia', clue: 'Asian American Adult Star' },
  { word: 'Lexi Belle', clue: 'Petite Blonde Adult Actress' },
  { word: 'Faye Reagan', clue: 'Redhead Adult Film Star' },
  { word: 'Shyla Stylez', clue: 'Canadian Adult Actress' },
  { word: 'Jessa Rhodes', clue: 'Blonde Adult Film Star' },
  { word: 'Carter Cruise', clue: 'Adult Star DJ' },
  { word: 'Remy LaCroix', clue: 'Adult Actress Hula Hooper' },
  { word: 'Proxy Paige', clue: 'Alternative Adult Performer' },
  { word: 'Cherie DeVille', clue: 'MILF Adult Film Star' },
  { word: 'India Summer', clue: 'MILF Category Icon' },
  { word: 'Nina Elle', clue: 'Blonde MILF Adult Star' },
  { word: 'Ava Addams', clue: 'Busty MILF Actress' },
  { word: 'Julia Ann', clue: 'Blonde MILF Legend' },
  { word: 'Priya Rai', clue: 'Indian Adult Film Star' },
  { word: 'Kendra Spade', clue: 'Asian American Adult Actress' },
  { word: 'Marica Hase', clue: 'Japanese Adult Film Star' },
  { word: 'Hitomi Tanaka', clue: 'Japanese Busty Adult Star' },
  { word: 'Anri Okita', clue: 'Japanese Gravure Adult Idol' },
  { word: 'Maria Ozawa', clue: 'Japanese Filipino Adult Star' },
  { word: 'Tia Tanaka', clue: 'Asian American Adult Actress' },
  { word: 'London Keyes', clue: 'Asian American Adult Star' },
  { word: 'Rae Lil Black', clue: 'Japanese American Gamer Adult Star' },
  { word: 'Kimmy Granger', clue: 'Petite Adult Film Actress' },
  { word: 'Ariana Marie', clue: 'Slender Adult Film Star' },
  { word: 'Kristen Scott', clue: 'Natural Adult Actress' },
  { word: 'Riley Nixon', clue: 'Alternative Adult Performer' },
  { word: 'Joanna Angel', clue: 'Punk Adult Star Director' },
  { word: 'Gina Valentina', clue: 'Brazilian Adult Film Star' },
  { word: 'Jynx Maze', clue: 'Latina Adult Actress' },
  { word: 'Kelsi Monroe', clue: 'Curvy Latina Adult Star' },
  { word: 'Rose Monroe', clue: 'Venezuelan Adult Actress' },
  { word: 'Luna Star', clue: 'Cuban Adult Film Star' },
  { word: 'Bridgette B', clue: 'Spanish Adult Film Actress' },
  { word: 'Diamond Kitty', clue: 'Cuban American Adult Star' },
  { word: 'Esperanza Gomez', clue: 'Colombian Adult Film Star' },
  { word: 'Franceska Jaimes', clue: 'Colombian Adult Actress' },
  { word: 'Sophie Dee', clue: 'Welsh Adult Film Star' },
  { word: 'Jasmine Jae', clue: 'British Adult Actress' },
  { word: 'Ava Dalush', clue: 'British Adult Film Star' },
  { word: 'Stella Cox', clue: 'British Italian Adult Star' },
  { word: 'Sienna Day', clue: 'British Adult Film Actress' },
  { word: 'Amirah Adara', clue: 'Hungarian Adult Star' },
  { word: 'Anissa Kate', clue: 'French Adult Film Star' },
  { word: 'Clea Gaultier', clue: 'French Adult Actress' },
  { word: 'Katsuni', clue: 'French Vietnamese Adult Legend' },
];
