export interface WordPair {
  word: string;
  clue: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export const animals: WordPair[] = [
  { word: 'Tiger', clue: 'Lion', difficulty: 'easy' },
  { word: 'Elephant', clue: 'Rhinoceros', difficulty: 'easy' },
  { word: 'Dolphin', clue: 'Whale', difficulty: 'medium' },
  { word: 'Eagle', clue: 'Hawk', difficulty: 'easy' },
  { word: 'Penguin', clue: 'Puffin', difficulty: 'medium' },
  { word: 'Kangaroo', clue: 'Wallaby', difficulty: 'medium' },
  { word: 'Cheetah', clue: 'Leopard', difficulty: 'easy' },
  { word: 'Giraffe', clue: 'Deer', difficulty: 'easy' },
  { word: 'Octopus', clue: 'Squid', difficulty: 'easy' },
  { word: 'Butterfly', clue: 'Moth', difficulty: 'easy' },
  { word: 'Crocodile', clue: 'Alligator', difficulty: 'medium' },
  { word: 'Peacock', clue: 'Pheasant', difficulty: 'hard' },
  { word: 'Panda', clue: 'Bear', difficulty: 'easy' },
  { word: 'Flamingo', clue: 'Crane', difficulty: 'medium' },
  { word: 'Koala', clue: 'Sloth', difficulty: 'medium' },
  { word: 'Owl', clue: 'Eagle', difficulty: 'easy' },
  { word: 'Fox', clue: 'Wolf', difficulty: 'easy' },
  { word: 'Zebra', clue: 'Horse', difficulty: 'easy' },
  { word: 'Parrot', clue: 'Macaw', difficulty: 'medium' },
  { word: 'Shark', clue: 'Barracuda', difficulty: 'medium' },
  { word: 'Gorilla', clue: 'Chimpanzee', difficulty: 'easy' },
  { word: 'Seal', clue: 'Sea Lion', difficulty: 'hard' },
  { word: 'Rabbit', clue: 'Hare', difficulty: 'hard' },
  { word: 'Swan', clue: 'Goose', difficulty: 'easy' },
  { word: 'Turtle', clue: 'Tortoise', difficulty: 'hard' },
  { word: 'Bee', clue: 'Wasp', difficulty: 'medium' },
  { word: 'Spider', clue: 'Scorpion', difficulty: 'medium' },
  { word: 'Frog', clue: 'Toad', difficulty: 'hard' },
  { word: 'Jellyfish', clue: 'Anemone', difficulty: 'hard' },
  { word: 'Camel', clue: 'Llama', difficulty: 'medium' },
  { word: 'Bat', clue: 'Bird', difficulty: 'medium' },
  { word: 'Hedgehog', clue: 'Porcupine', difficulty: 'hard' },
  { word: 'Lobster', clue: 'Crab', difficulty: 'easy' },
  { word: 'Salamander', clue: 'Lizard', difficulty: 'medium' },
  { word: 'Stingray', clue: 'Manta Ray', difficulty: 'hard' },
  { word: 'Ostrich', clue: 'Emu', difficulty: 'hard' },
  { word: 'Raccoon', clue: 'Badger', difficulty: 'medium' },
  { word: 'Squirrel', clue: 'Chipmunk', difficulty: 'medium' },
  { word: 'Hippo', clue: 'Rhino', difficulty: 'medium' },
  { word: 'Cobra', clue: 'Python', difficulty: 'medium' },
  { word: 'Pigeon', clue: 'Dove', difficulty: 'hard' },
  { word: 'Moose', clue: 'Elk', difficulty: 'hard' },
  { word: 'Hamster', clue: 'Guinea Pig', difficulty: 'medium' },
  { word: 'Goldfish', clue: 'Koi', difficulty: 'medium' },
  { word: 'Starfish', clue: 'Sea Urchin', difficulty: 'hard' },
  { word: 'Chameleon', clue: 'Iguana', difficulty: 'medium' },
  { word: 'Platypus', clue: 'Otter', difficulty: 'hard' },
  { word: 'Walrus', clue: 'Seal', difficulty: 'medium' },
  { word: 'Lynx', clue: 'Bobcat', difficulty: 'hard' },
  { word: 'Meerkat', clue: 'Prairie Dog', difficulty: 'hard' },
];
