export const bollywoodMovies = [
  // Blockbusters
  { word: '3 Idiots', clue: 'Engineering College Comedy' },
  { word: 'Dangal', clue: 'Wrestling Daughters Story' },
  { word: 'PK', clue: 'Alien Questions Religion' },
  { word: 'Baahubali', clue: 'South Indian Epic War' },
  { word: 'Pathaan', clue: 'Shah Rukh Spy Action' },
  { word: 'Jawan', clue: 'Shah Rukh Double Role' },
  { word: 'Padmaavat', clue: 'Rajput Queen Historical' },
  { word: 'Bajirao Mastani', clue: 'Peshwa Love Story' },
  { word: 'Chennai Express', clue: 'Train Journey South Romance' },
  { word: 'Dhoom 3', clue: 'Circus Heist Thriller' },
  { word: 'Krrish', clue: 'Indian Superhero Franchise' },
  { word: 'Kabir Singh', clue: 'Toxic Love Medical Student' },
  { word: 'Sanju', clue: 'Sanjay Dutt Biopic' },
  { word: 'War', clue: 'Agent vs Agent Action' },
  { word: 'Uri', clue: 'Surgical Strike Military' },
  { word: 'Raees', clue: 'Gujarat Gangster Bootlegger' },
  { word: 'Sultan', clue: 'Wrestler Comeback Story' },
  { word: 'Bajrangi Bhaijaan', clue: 'Lost Girl Pakistan' },
  { word: 'Prem Ratan Dhan Payo', clue: 'Double Role Prince' },
  { word: 'Simmba', clue: 'Corrupt Cop Reform' },
  { word: 'Singham', clue: 'Honest Police Officer' },
  { word: 'Dabangg', clue: 'Chulbul Pandey Cop' },
  { word: 'Golmaal', clue: 'Comedy Franchise Gang' },
  { word: 'Housefull', clue: 'Comedy Confusion Series' },
  { word: 'Welcome', clue: 'Gangster Family Comedy' },
  { word: 'Hera Pheri', clue: 'Trio Money Scheme' },
  { word: 'Andaz Apna Apna', clue: 'Classic Comedy Cult' },
  { word: 'Chupke Chupke', clue: 'Professor Language Comedy' },
  { word: 'Sholay', clue: 'Jai Veeru Gabbar Classic' },
  { word: 'Dilwale Dulhania Le Jayenge', clue: 'DDLJ Train Romance' },
  { word: 'Kuch Kuch Hota Hai', clue: 'Friendship Love Triangle' },
  { word: 'Kabhi Khushi Kabhie Gham', clue: 'Family Joint Big Fat' },
  { word: 'Kal Ho Naa Ho', clue: 'Heart Patient Love' },
  { word: 'Veer-Zaara', clue: 'India Pakistan Love' },
  { word: 'Jab We Met', clue: 'Train Journey Love' },
  { word: 'Rab Ne Bana Di Jodi', clue: 'Shy Husband Makeover' },
  { word: 'Om Shanti Om', clue: 'Reincarnation Bollywood' },
  { word: 'Ra.One', clue: 'Video Game Villain' },
  { word: 'Devdas', clue: 'Alcohol Tragic Love' },
  { word: 'Lagaan', clue: 'Cricket Colonial India' },
  { word: 'Taare Zameen Par', clue: 'Dyslexic Child Teacher' },
  { word: 'Rang De Basanti', clue: 'Revolution Youth Awakening' },
  { word: 'Chak De India', clue: 'Women Hockey Coach' },
  { word: 'Swades', clue: 'NASA Engineer Village' },
  { word: 'Munna Bhai MBBS', clue: 'Gangster Medical College' },
  { word: 'Lage Raho Munna Bhai', clue: 'Gandhi Radio RJ' },
  { word: 'Dil Chahta Hai', clue: 'Three Friends Modern' },
  { word: 'Zindagi Na Milegi Dobara', clue: 'Spain Bachelor Trip' },
  { word: 'Yeh Jawaani Hai Deewani', clue: 'Travel Wedding Friendship' },
  { word: 'Rockstar', clue: 'Musician Heartbreak Journey' },
  { word: 'Barfi', clue: 'Deaf Mute Love' },
  { word: 'Queen', clue: 'Solo Honeymoon Paris' },
  { word: 'Pink', clue: 'No Means No Consent' },
  { word: 'Airlift', clue: 'Kuwait Evacuation Mission' },
  { word: 'Rustom', clue: 'Navy Officer Murder Trial' },
  { word: 'Toilet Ek Prem Katha', clue: 'Sanitation Social Message' },
  { word: 'Pad Man', clue: 'Menstrual Hygiene Innovation' },
  { word: 'Andhadhun', clue: 'Blind Pianist Thriller' },
  { word: 'Article 15', clue: 'Caste Discrimination Police' },
  { word: 'Gully Boy', clue: 'Mumbai Rap Underdog' },
  { word: 'Chhichhore', clue: 'College Hostel Reunion' },
  { word: 'Super 30', clue: 'IIT Coaching True Story' },
  { word: 'Mission Mangal', clue: 'Mars Mission ISRO' },
  { word: 'Tanhaji', clue: 'Maratha Warrior Historical' },
  { word: 'Shershaah', clue: 'Kargil War Captain Vikram' },
  { word: 'Kesari', clue: 'Battle of Saragarhi' },
  { word: 'The Kashmir Files', clue: 'Kashmiri Pandit Exodus' },
  { word: 'Kantara', clue: 'Kannada Folklore Thriller' },
  { word: 'KGF', clue: 'Gold Mine Gangster' },
  { word: 'Pushpa', clue: 'Red Sandalwood Smuggler' },
  { word: 'RRR', clue: 'Freedom Fighters Friendship' },
  { word: 'Brahmastra', clue: 'Mystical Powers Trilogy' },
  { word: 'Gangubai Kathiawadi', clue: 'Madam Brothel Mumbai' },
  { word: 'Bhool Bhulaiyaa', clue: 'Haunted Palace Psychiatrist' },
  { word: 'Stree', clue: 'Ghost Woman Horror Comedy' },
  { word: 'Tumbbad', clue: 'Greed Demon Folklore' },
  { word: 'Drishyam', clue: 'Perfect Crime Family Protection' },
  { word: 'Kahaani', clue: 'Pregnant Woman Missing Husband' },
  { word: 'A Wednesday', clue: 'Common Man Terrorist Threat' },
  { word: 'Special 26', clue: 'Fake CBI Heist' },
  { word: 'Baby', clue: 'Counter Intelligence Team' },
  { word: 'Raazi', clue: 'Indian Spy Pakistan' },
  { word: 'Talvar', clue: 'Aarushi Murder Case' },
  { word: 'Udta Punjab', clue: 'Drug Crisis Punjab' },
  { word: 'NH10', clue: 'Highway Honor Killing' },
  { word: 'Masaan', clue: 'Varanasi Small Town Stories' },
  { word: 'Newton', clue: 'Election Duty Naxal Area' },
  { word: 'Raazi', clue: 'Woman Spy Kashmir' },
];
