export interface WordPair {
  word: string;
  clue: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export const brands: WordPair[] = [
  { word: 'Apple', clue: 'Samsung', difficulty: 'easy' },
  { word: 'Nike', clue: 'Adidas', difficulty: 'easy' },
  { word: 'Coca-Cola', clue: 'Pepsi', difficulty: 'easy' },
  { word: 'McDonald\'s', clue: 'Burger King', difficulty: 'easy' },
  { word: 'Starbucks', clue: 'Dunkin\'', difficulty: 'easy' },
  { word: 'Google', clue: 'Microsoft', difficulty: 'easy' },
  { word: 'Amazon', clue: 'eBay', difficulty: 'easy' },
  { word: 'Netflix', clue: 'Hulu', difficulty: 'easy' },
  { word: 'Spotify', clue: 'Apple Music', difficulty: 'medium' },
  { word: 'PlayStation', clue: 'Xbox', difficulty: 'easy' },
  { word: 'Nintendo', clue: 'Sega', difficulty: 'easy' },
  { word: 'Tesla', clue: 'Rivian', difficulty: 'medium' },
  { word: 'Ford', clue: 'Chevrolet', difficulty: 'easy' },
  { word: 'BMW', clue: 'Mercedes-Benz', difficulty: 'easy' },
  { word: 'Toyota', clue: 'Honda', difficulty: 'easy' },
  { word: 'Ferrari', clue: 'Lamborghini', difficulty: 'easy' },
  { word: 'Porsche', clue: 'Audi', difficulty: 'medium' },
  { word: 'Rolex', clue: 'Omega', difficulty: 'medium' },
  { word: 'Gucci', clue: 'Prada', difficulty: 'medium' },
  { word: 'Louis Vuitton', clue: 'Chanel', difficulty: 'medium' },
  { word: 'Versace', clue: 'Armani', difficulty: 'medium' },
  { word: 'Zara', clue: 'H&M', difficulty: 'easy' },
  { word: 'Uniqlo', clue: 'Gap', difficulty: 'medium' },
  { word: 'Levi\'s', clue: 'Wrangler', difficulty: 'medium' },
  { word: 'Converse', clue: 'Vans', difficulty: 'easy' },
  { word: 'Puma', clue: 'Reebok', difficulty: 'easy' },
  { word: 'Under Armour', clue: 'New Balance', difficulty: 'medium' },
  { word: 'Disney', clue: 'Universal', difficulty: 'easy' },
  { word: 'Warner Bros', clue: 'Paramount', difficulty: 'hard' },
  { word: 'Marvel', clue: 'DC Comics', difficulty: 'easy' },
  { word: 'Pixar', clue: 'DreamWorks', difficulty: 'easy' },
  { word: 'YouTube', clue: 'Vimeo', difficulty: 'easy' },
  { word: 'TikTok', clue: 'Instagram', difficulty: 'easy' },
  { word: 'Facebook', clue: 'Twitter', difficulty: 'easy' },
  { word: 'Snapchat', clue: 'WhatsApp', difficulty: 'medium' },
  { word: 'LinkedIn', clue: 'Indeed', difficulty: 'hard' },
  { word: 'Uber', clue: 'Lyft', difficulty: 'easy' },
  { word: 'Airbnb', clue: 'VRBO', difficulty: 'medium' },
  { word: 'DoorDash', clue: 'Uber Eats', difficulty: 'medium' },
  { word: 'KFC', clue: 'Popeyes', difficulty: 'easy' },
  { word: 'Subway', clue: 'Jimmy John\'s', difficulty: 'medium' },
  { word: 'Domino\'s', clue: 'Pizza Hut', difficulty: 'easy' },
  { word: 'Taco Bell', clue: 'Chipotle', difficulty: 'easy' },
  { word: 'Wendy\'s', clue: 'Arby\'s', difficulty: 'medium' },
  { word: 'IKEA', clue: 'Ashley Furniture', difficulty: 'medium' },
  { word: 'Target', clue: 'Walmart', difficulty: 'easy' },
  { word: 'Costco', clue: 'Sam\'s Club', difficulty: 'easy' },
  { word: 'Best Buy', clue: 'Circuit City', difficulty: 'hard' },
  { word: 'Home Depot', clue: 'Lowe\'s', difficulty: 'easy' },
  { word: 'Visa', clue: 'Mastercard', difficulty: 'easy' },
];
