export const cartoonCharacters = [
  // Classic Cartoons
  { word: 'Mickey Mouse', clue: 'Disney Iconic Mouse' },
  { word: 'Donald Duck', clue: 'Angry Sailor Duck' },
  { word: 'Goofy', clue: 'Clumsy Tall Dog' },
  { word: 'Bugs Bunny', clue: 'What\'s Up Doc Rabbit' },
  { word: 'Daffy Duck', clue: 'Looney Tunes Duck' },
  { word: 'Tom and Jerry', clue: 'Cat Mouse Chase' },
  { word: 'Scooby-Doo', clue: 'Mystery Solving Dog' },
  { word: 'Shaggy', clue: 'Scooby Best Friend' },
  { word: 'Fred Flintstone', clue: 'Stone Age Family Man' },
  { word: 'Barney Rubble', clue: 'Fred\'s Neighbor' },
  { word: 'Popeye', clue: 'Spinach Sailor Man' },
  { word: 'Olive Oyl', clue: 'Popeye\'s Girlfriend' },
  { word: 'SpongeBob SquarePants', clue: 'Underwater Fry Cook' },
  { word: 'Patrick Star', clue: 'Pink Starfish Friend' },
  { word: 'Squidward', clue: 'Grumpy Octopus Neighbor' },
  { word: 'Sandy Cheeks', clue: 'Underwater Squirrel' },
  { word: 'Homer Simpson', clue: 'D\'oh Yellow Father' },
  { word: 'Bart Simpson', clue: 'Skateboard Prankster Kid' },
  { word: 'Lisa Simpson', clue: 'Saxophone Smart Sister' },
  { word: 'Marge Simpson', clue: 'Blue Hair Mother' },
  { word: 'Peter Griffin', clue: 'Fat Chicken Fighter' },
  { word: 'Stewie Griffin', clue: 'Evil Baby Genius' },
  { word: 'Brian Griffin', clue: 'Talking Family Dog' },
  { word: 'Lois Griffin', clue: 'Peter\'s Wife' },
  { word: 'Stan Smith', clue: 'CIA Agent Father' },
  { word: 'Roger', clue: 'Alien Living Attic' },
  { word: 'Cartman', clue: 'Fat South Park Kid' },
  { word: 'Kenny', clue: 'Dies Every Episode' },
  { word: 'Kyle', clue: 'Jewish South Park Boy' },
  { word: 'Stan Marsh', clue: 'South Park Main Kid' },
  { word: 'Rick Sanchez', clue: 'Genius Scientist Grandpa' },
  { word: 'Morty Smith', clue: 'Anxious Grandson Sidekick' },
  { word: 'Bender', clue: 'Robot Drinks Smokes' },
  { word: 'Fry', clue: 'Future Delivery Boy' },
  { word: 'Leela', clue: 'One Eyed Pilot' },
  { word: 'Shrek', clue: 'Green Swamp Ogre' },
  { word: 'Donkey', clue: 'Talking Shrek Friend' },
  { word: 'Fiona', clue: 'Princess Ogre Wife' },
  { word: 'Puss in Boots', clue: 'Sword Fighting Cat' },
  { word: 'Woody', clue: 'Cowboy Toy Sheriff' },
  { word: 'Buzz Lightyear', clue: 'Space Ranger Toy' },
  { word: 'Lightning McQueen', clue: 'Racing Red Car' },
  { word: 'Mater', clue: 'Tow Truck Friend' },
  { word: 'Mike Wazowski', clue: 'One Eyed Green Monster' },
  { word: 'Sulley', clue: 'Big Blue Furry Monster' },
  { word: 'Nemo', clue: 'Lost Clownfish Son' },
  { word: 'Dory', clue: 'Forgetful Blue Fish' },
  { word: 'Simba', clue: 'Lion Prince Cub' },
  { word: 'Mufasa', clue: 'Lion King Father' },
  { word: 'Timon and Pumbaa', clue: 'Hakuna Matata Duo' },
  { word: 'Elsa', clue: 'Ice Queen Let It Go' },
  { word: 'Anna', clue: 'Elsa\'s Sister Princess' },
  { word: 'Olaf', clue: 'Warm Hugs Snowman' },
  { word: 'Moana', clue: 'Ocean Sailing Princess' },
  { word: 'Maui', clue: 'Demigod Shapeshifter' },
  { word: 'Rapunzel', clue: 'Long Hair Tower Princess' },
  { word: 'Flynn Rider', clue: 'Thief Charming Rogue' },
  { word: 'Aladdin', clue: 'Street Rat Genie Lamp' },
  { word: 'Jasmine', clue: 'Arabian Princess Tiger' },
  { word: 'Genie', clue: 'Blue Wish Granting' },
  { word: 'Ariel', clue: 'Mermaid Princess Voice' },
  { word: 'Belle', clue: 'Beauty Beast Library' },
  { word: 'Cinderella', clue: 'Glass Slipper Midnight' },
  { word: 'Snow White', clue: 'Seven Dwarfs Apple' },
  { word: 'Mulan', clue: 'Warrior Disguised Girl' },
  { word: 'Pocahontas', clue: 'Native American Princess' },
  { word: 'Tiana', clue: 'Frog Kiss Princess' },
  { word: 'Merida', clue: 'Brave Redhead Archer' },
  { word: 'Stitch', clue: 'Blue Alien Experiment' },
  { word: 'Lilo', clue: 'Hawaiian Girl Alien' },
  { word: 'Pikachu', clue: 'Electric Yellow Mouse' },
  { word: 'Ash Ketchum', clue: 'Pokemon Trainer Boy' },
  { word: 'Naruto', clue: 'Ninja Orange Jumpsuit' },
  { word: 'Goku', clue: 'Saiyan Super Powers' },
  { word: 'Luffy', clue: 'Rubber Pirate Captain' },
  { word: 'Doraemon', clue: 'Blue Robot Cat' },
  { word: 'Totoro', clue: 'Giant Forest Spirit' },
  { word: 'Gru', clue: 'Villain Adopts Girls' },
  { word: 'Minion', clue: 'Yellow Pill Servant' },
  { word: 'Po', clue: 'Kung Fu Panda Warrior' },
  { word: 'Hiccup', clue: 'Dragon Trainer Viking' },
  { word: 'Toothless', clue: 'Night Fury Dragon' },
  { word: 'Dora', clue: 'Explorer Backpack Map' },
  { word: 'Boots', clue: 'Dora\'s Monkey Friend' },
  { word: 'Blue', clue: 'Blue Dog Clues' },
  { word: 'Peppa Pig', clue: 'British Pink Pig' },
  { word: 'Bluey', clue: 'Australian Blue Dog' },
  { word: 'Paw Patrol', clue: 'Rescue Puppy Team' },
  { word: 'Ben 10', clue: 'Alien Watch Transforming' },
  { word: 'Gwen', clue: 'Ben\'s Magic Cousin' },
  { word: 'Avatar Aang', clue: 'Last Airbender Monk' },
  { word: 'Katara', clue: 'Waterbender Girl' },
  { word: 'Zuko', clue: 'Scarred Fire Prince' },
  { word: 'Korra', clue: 'Next Avatar Waterbender' },
];
