export interface WordPair {
  word: string;
  clue: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export const celebrities: WordPair[] = [
  { word: 'Taylor Swift', clue: 'Ariana Grande', difficulty: 'easy' },
  { word: 'Tom Cruise', clue: 'Brad Pitt', difficulty: 'easy' },
  { word: 'Beyoncé', clue: 'Rihanna', difficulty: 'easy' },
  { word: 'Leonardo DiCaprio', clue: 'Matt Damon', difficulty: 'easy' },
  { word: 'Oprah Winfrey', clue: 'Ellen DeGeneres', difficulty: 'easy' },
  { word: 'Cristiano Ronaldo', clue: 'Lionel Messi', difficulty: 'easy' },
  { word: 'Dwayne Johnson', clue: 'Vin Diesel', difficulty: 'easy' },
  { word: 'Jennifer Lawrence', clue: 'Emma Stone', difficulty: 'medium' },
  { word: 'Chris Hemsworth', clue: 'Chris Evans', difficulty: 'medium' },
  { word: 'Zendaya', clue: 'Timothée Chalamet', difficulty: 'medium' },
  { word: 'Kanye West', clue: 'Drake', difficulty: 'easy' },
  { word: 'Lady Gaga', clue: 'Katy Perry', difficulty: 'easy' },
  { word: 'Ed Sheeran', clue: 'Shawn Mendes', difficulty: 'medium' },
  { word: 'Billie Eilish', clue: 'Olivia Rodrigo', difficulty: 'medium' },
  { word: 'The Weeknd', clue: 'Bruno Mars', difficulty: 'medium' },
  { word: 'Robert Downey Jr.', clue: 'Chris Pratt', difficulty: 'medium' },
  { word: 'Scarlett Johansson', clue: 'Margot Robbie', difficulty: 'medium' },
  { word: 'Will Smith', clue: 'Denzel Washington', difficulty: 'medium' },
  { word: 'Meryl Streep', clue: 'Nicole Kidman', difficulty: 'hard' },
  { word: 'Johnny Depp', clue: 'Jared Leto', difficulty: 'medium' },
  { word: 'Angelina Jolie', clue: 'Charlize Theron', difficulty: 'medium' },
  { word: 'Ryan Reynolds', clue: 'Ryan Gosling', difficulty: 'easy' },
  { word: 'Emma Watson', clue: 'Emma Thompson', difficulty: 'hard' },
  { word: 'Tom Hanks', clue: 'Tom Hardy', difficulty: 'medium' },
  { word: 'Morgan Freeman', clue: 'Samuel L. Jackson', difficulty: 'medium' },
  { word: 'Keanu Reeves', clue: 'Joaquin Phoenix', difficulty: 'medium' },
  { word: 'Adele', clue: 'Sam Smith', difficulty: 'medium' },
  { word: 'Justin Bieber', clue: 'Justin Timberlake', difficulty: 'easy' },
  { word: 'Selena Gomez', clue: 'Demi Lovato', difficulty: 'easy' },
  { word: 'Miley Cyrus', clue: 'Britney Spears', difficulty: 'easy' },
  { word: 'Post Malone', clue: 'Lil Nas X', difficulty: 'medium' },
  { word: 'Cardi B', clue: 'Nicki Minaj', difficulty: 'easy' },
  { word: 'Harry Styles', clue: 'Zayn Malik', difficulty: 'medium' },
  { word: 'Dua Lipa', clue: 'Camila Cabello', difficulty: 'medium' },
  { word: 'BTS', clue: 'BLACKPINK', difficulty: 'easy' },
  { word: 'Michael Jordan', clue: 'LeBron James', difficulty: 'easy' },
  { word: 'Serena Williams', clue: 'Venus Williams', difficulty: 'medium' },
  { word: 'Usain Bolt', clue: 'Carl Lewis', difficulty: 'hard' },
  { word: 'Tiger Woods', clue: 'Phil Mickelson', difficulty: 'hard' },
  { word: 'Roger Federer', clue: 'Rafael Nadal', difficulty: 'easy' },
  { word: 'Elon Musk', clue: 'Jeff Bezos', difficulty: 'easy' },
  { word: 'Mark Zuckerberg', clue: 'Bill Gates', difficulty: 'easy' },
  { word: 'Steve Jobs', clue: 'Steve Wozniak', difficulty: 'hard' },
  { word: 'Barack Obama', clue: 'Joe Biden', difficulty: 'easy' },
  { word: 'Donald Trump', clue: 'Boris Johnson', difficulty: 'medium' },
  { word: 'Kim Kardashian', clue: 'Kylie Jenner', difficulty: 'easy' },
  { word: 'Gordon Ramsay', clue: 'Jamie Oliver', difficulty: 'easy' },
  { word: 'Mr. Beast', clue: 'PewDiePie', difficulty: 'easy' },
  { word: 'Jimmy Fallon', clue: 'Jimmy Kimmel', difficulty: 'hard' },
  { word: 'Stephen Curry', clue: 'Klay Thompson', difficulty: 'medium' },
];
