export const cricketers = [
  // Indian Cricketers
  { word: 'Virat Kohli', clue: 'Famous Indian Batsman' },
    { word: 'Sachin Tendulkar', clue: 'Cricket Legend' },
    { word: 'MS Dhoni', clue: 'Indian Captain & Wicketkeeper' },
    { word: 'Rohit Sharma', clue: 'Indian Opener' },
    { word: 'Jasprit Bumrah', clue: 'Fast Bowler' },
    { word: 'Hardik Pandya', clue: 'All-Rounder' },
    { word: 'KL Rahul', clue: 'Indian Batsman' },
    { word: 'Ravindra Jadeja', clue: 'Spin All-Rounder' },
    { word: 'Rishabh Pant', clue: 'Wicketkeeper Batsman' },
    { word: 'Shubman Gill', clue: 'Young Indian Opener' },
    { word: 'Suryakumar Yadav', clue: 'T20 Specialist' },
    { word: 'Yuvraj Singh', clue: '2011 World Cup Hero' },
    { word: 'Kapil Dev', clue: '1983 World Cup Captain' },
    { word: 'Rahul Dravid', clue: 'The Wall' },
    { word: 'Sourav Ganguly', clue: 'Dada - Former Captain' },
    { word: 'Anil Kumble', clue: 'Legendary Spinner' },
    { word: 'Harbhajan Singh', clue: 'Off Spinner' },
    { word: 'Zaheer Khan', clue: 'Left-Arm Fast Bowler' },
    { word: 'Gautam Gambhir', clue: 'World Cup Final Hero' },
    { word: 'Virender Sehwag', clue: 'Aggressive Opener' },
    { word: 'VVS Laxman', clue: 'Eden Gardens Hero' },
    { word: 'Mohammad Kaif', clue: 'Natwest Trophy Hero' },
    { word: 'Sunil Gavaskar', clue: 'First Test Great' },
    { word: 'Ravi Shastri', clue: 'Coach & Former Player' },
    { word: 'Irfan Pathan', clue: 'Swing Bowler' },
    { word: 'RP Singh', clue: 'T20 World Cup Bowler' },
    { word: 'Ajinkya Rahane', clue: 'Test Vice Captain' },
    { word: 'Cheteshwar Pujara', clue: 'Test Specialist' },
    { word: 'Mohammed Shami', clue: 'Fast Bowler' },
    { word: 'Ravichandran Ashwin', clue: 'Premier Off Spinner' },
    
    // International Cricketers
    { word: 'AB de Villiers', clue: 'South African Superman' },
    { word: 'Steve Smith', clue: 'Australian Batsman' },
    { word: 'David Warner', clue: 'Aussie Opener' },
    { word: 'Kane Williamson', clue: 'New Zealand Captain' },
    { word: 'Joe Root', clue: 'English Captain' },
    { word: 'Ben Stokes', clue: 'English All-Rounder' },
    { word: 'Babar Azam', clue: 'Pakistani Captain' },
    { word: 'Shaheen Afridi', clue: 'Pakistani Fast Bowler' },
    { word: 'Rashid Khan', clue: 'Afghan Leg Spinner' },
    { word: 'Chris Gayle', clue: 'Universe Boss' },
    { word: 'Andre Russell', clue: 'West Indian All-Rounder' },
    { word: 'Glenn Maxwell', clue: 'Big Show' },
    { word: 'Pat Cummins', clue: 'Australian Captain' },
    { word: 'Mitchell Starc', clue: 'Left-Arm Pacer' },
    { word: 'Josh Hazlewood', clue: 'Australian Bowler' },
    { word: 'Trent Boult', clue: 'Kiwi Swing Bowler' },
    { word: 'Kagiso Rabada', clue: 'South African Pacer' },
    { word: 'Quinton de Kock', clue: 'Wicketkeeper Batsman' },
    { word: 'Jonny Bairstow', clue: 'English Wicketkeeper' },
    { word: 'Jos Buttler', clue: 'English Captain' },
    { word: 'Shakib Al Hasan', clue: 'Bangladesh All-Rounder' },
    { word: 'Tamim Iqbal', clue: 'Bangladesh Opener' },
    { word: 'Angelo Mathews', clue: 'Sri Lankan All-Rounder' },
    { word: 'Lasith Malinga', clue: 'Slinga Malinga' },
    { word: 'Kumar Sangakkara', clue: 'Sri Lankan Legend' },
    { word: 'Mahela Jayawardene', clue: 'Sri Lankan Great' },
    { word: 'Dale Steyn', clue: 'South African Legend' },
    { word: 'Jacques Kallis', clue: 'All-Time Great All-Rounder' },
    { word: 'Ricky Ponting', clue: 'Australian Legend' },
    { word: 'Shane Warne', clue: 'Legendary Leg Spinner' },
    { word: 'Glenn McGrath', clue: 'Australian Fast Bowler' },
    { word: 'Brett Lee', clue: 'Aussie Express' },
    { word: 'Brian Lara', clue: 'West Indian Legend' },
    { word: 'Viv Richards', clue: 'Master Blaster' },
    { word: 'Wasim Akram', clue: 'Sultan of Swing' },
    { word: 'Waqar Younis', clue: 'Pakistani Pacer' },
    { word: 'Shoaib Akhtar', clue: 'Rawalpindi Express' },
    { word: 'Imran Khan', clue: 'Pakistani Captain' },
    { word: 'Javed Miandad', clue: 'Pakistani Legend' },
    { word: 'Inzamam-ul-Haq', clue: 'Pakistani Batsman' },
    { word: 'Kevin Pietersen', clue: 'English Batsman' },
    { word: 'Andrew Flintoff', clue: 'English All-Rounder' },
    { word: 'James Anderson', clue: 'English Swing Bowler' },
    { word: 'Stuart Broad', clue: 'English Fast Bowler' },
    { word: 'Hashim Amla', clue: 'South African Batsman' },
    { word: 'Faf du Plessis', clue: 'South African Captain' },
    { word: 'Martin Guptill', clue: 'Kiwi Opener' },
    { word: 'Ross Taylor', clue: 'New Zealand Batsman' },
    { word: 'Brendon McCullum', clue: 'Baz - Former Captain' },
    { word: 'Daniel Vettori', clue: 'Kiwi Spinner' },
    { word: 'Mitchell Johnson', clue: 'Australian Pacer' },
    { word: 'Michael Clarke', clue: 'Aussie Captain' },
    { word: 'Adam Gilchrist', clue: 'Legendary Keeper' },
    { word: 'Matthew Hayden', clue: 'Australian Opener' },
    { word: 'Justin Langer', clue: 'Australian Coach' },
  { word: 'Mark Waugh', clue: 'Junior Waugh' },
  { word: 'Steve Waugh', clue: 'Australian Captain' },
];