export interface WordPair {
  word: string;
  clue: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export const foodDrinks: WordPair[] = [
  { word: 'Pizza', clue: 'Pasta', difficulty: 'easy' },
  { word: 'Burger', clue: 'Sandwich', difficulty: 'easy' },
  { word: 'Sushi', clue: 'Sashimi', difficulty: 'medium' },
  { word: 'Taco', clue: 'Burrito', difficulty: 'easy' },
  { word: 'Steak', clue: 'Ribs', difficulty: 'medium' },
  { word: 'Chicken', clue: 'Turkey', difficulty: 'easy' },
  { word: 'Salmon', clue: 'Tuna', difficulty: 'easy' },
  { word: 'Shrimp', clue: 'Prawn', difficulty: 'hard' },
  { word: 'Lobster', clue: 'Crab', difficulty: 'easy' },
  { word: 'Ramen', clue: 'Udon', difficulty: 'medium' },
  { word: 'Pho', clue: 'Ramen', difficulty: 'medium' },
  { word: 'Pad Thai', clue: 'Lo Mein', difficulty: 'hard' },
  { word: 'Curry', clue: 'Stew', difficulty: 'medium' },
  { word: 'Fried Rice', clue: 'Fried Noodles', difficulty: 'medium' },
  { word: 'Dumpling', clue: 'Wonton', difficulty: 'hard' },
  { word: 'Spring Roll', clue: 'Egg Roll', difficulty: 'hard' },
  { word: 'Croissant', clue: 'Bagel', difficulty: 'medium' },
  { word: 'Donut', clue: 'Muffin', difficulty: 'easy' },
  { word: 'Pancake', clue: 'Waffle', difficulty: 'easy' },
  { word: 'French Toast', clue: 'Toast', difficulty: 'medium' },
  { word: 'Omelette', clue: 'Scrambled Eggs', difficulty: 'medium' },
  { word: 'Bacon', clue: 'Sausage', difficulty: 'easy' },
  { word: 'Hot Dog', clue: 'Corn Dog', difficulty: 'medium' },
  { word: 'Nachos', clue: 'Chips and Salsa', difficulty: 'medium' },
  { word: 'Quesadilla', clue: 'Enchilada', difficulty: 'hard' },
  { word: 'Falafel', clue: 'Hummus', difficulty: 'hard' },
  { word: 'Kebab', clue: 'Shawarma', difficulty: 'hard' },
  { word: 'Paella', clue: 'Risotto', difficulty: 'hard' },
  { word: 'Goulash', clue: 'Stew', difficulty: 'hard' },
  { word: 'Lasagna', clue: 'Ravioli', difficulty: 'medium' },
  { word: 'Spaghetti', clue: 'Linguine', difficulty: 'hard' },
  { word: 'Mac and Cheese', clue: 'Cheese Pasta', difficulty: 'medium' },
  { word: 'Chili', clue: 'Soup', difficulty: 'medium' },
  { word: 'Salad', clue: 'Coleslaw', difficulty: 'medium' },
  { word: 'Caesar Salad', clue: 'Greek Salad', difficulty: 'hard' },
  { word: 'Ice Cream', clue: 'Gelato', difficulty: 'medium' },
  { word: 'Cake', clue: 'Cupcake', difficulty: 'easy' },
  { word: 'Brownie', clue: 'Cookie', difficulty: 'easy' },
  { word: 'Cheesecake', clue: 'Tiramisu', difficulty: 'medium' },
  { word: 'Pudding', clue: 'Custard', difficulty: 'hard' },
  { word: 'Pie', clue: 'Tart', difficulty: 'medium' },
  { word: 'Coffee', clue: 'Espresso', difficulty: 'medium' },
  { word: 'Tea', clue: 'Green Tea', difficulty: 'easy' },
  { word: 'Latte', clue: 'Cappuccino', difficulty: 'hard' },
  { word: 'Smoothie', clue: 'Milkshake', difficulty: 'easy' },
  { word: 'Juice', clue: 'Nectar', difficulty: 'medium' },
  { word: 'Soda', clue: 'Pop', difficulty: 'hard' },
  { word: 'Lemonade', clue: 'Iced Tea', difficulty: 'medium' },
  { word: 'Hot Chocolate', clue: 'Cocoa', difficulty: 'hard' },
  { word: 'Wine', clue: 'Champagne', difficulty: 'easy' },
  { word: 'Beer', clue: 'Ale', difficulty: 'medium' },
];
