export const hollywoodMovies = [
  // Already included in movies.ts, but adding more specific ones
  { word: 'The Godfather', clue: 'Mafia Family Saga' },
  { word: 'Pulp Fiction', clue: 'Tarantino Crime Anthology' },
  { word: 'The Shawshank Redemption', clue: 'Prison Escape Hope' },
  { word: 'Forrest Gump', clue: 'Running Life Journey' },
  { word: 'Inception', clue: 'Dream Within Dream' },
  { word: 'The Dark Knight', clue: 'Batman Joker Masterpiece' },
  { word: 'Fight Club', clue: 'First Rule No Talking' },
  { word: 'The Matrix', clue: 'Virtual Reality Red Pill' },
  { word: 'Goodfellas', clue: 'Wiseguy Mafia Life' },
  { word: 'The Silence of the Lambs', clue: 'Hannibal Lecter FBI' },
  { word: 'Saving Private Ryan', clue: 'D Day War Mission' },
  { word: 'Interstellar', clue: 'Space Time Relativity' },
  { word: 'Gladiator', clue: 'Roman General Slave' },
  { word: 'The Green Mile', clue: 'Death Row Miracles' },
  { word: 'Titanic', clue: 'Ship Sinking Romance' },
  { word: 'Avatar', clue: 'Pandora Blue Aliens' },
  { word: 'Avengers Endgame', clue: 'Infinity War Conclusion' },
  { word: 'Jurassic Park', clue: 'Dinosaur Island Chaos' },
  { word: 'Star Wars', clue: 'Space Opera Epic' },
  { word: 'The Lord of the Rings', clue: 'Fellowship Ring Quest' },
  { word: 'Harry Potter', clue: 'Boy Wizard Hogwarts' },
  { word: 'The Lion King', clue: 'Pride Rock Circle Life' },
  { word: 'Toy Story', clue: 'Toys Come Alive' },
  { word: 'Finding Nemo', clue: 'Father Fish Search' },
  { word: 'Frozen', clue: 'Let It Go Sisters' },
  { word: 'The Terminator', clue: 'Cyborg Time Travel' },
  { word: 'Alien', clue: 'Space Horror Xenomorph' },
  { word: 'Predator', clue: 'Jungle Invisible Hunter' },
  { word: 'Die Hard', clue: 'Skyscraper Hostage Hero' },
  { word: 'The Shining', clue: 'Hotel Winter Madness' },
  { word: 'The Exorcist', clue: 'Demon Possession Girl' },
  { word: 'Psycho', clue: 'Motel Shower Scene' },
  { word: 'Jaws', clue: 'Beach Shark Terror' },
  { word: 'E.T.', clue: 'Phone Home Alien' },
  { word: 'Back to the Future', clue: 'DeLorean Time Travel' },
  { word: 'Ghostbusters', clue: 'Who You Gonna Call' },
  { word: 'Indiana Jones', clue: 'Archaeologist Adventure Whip' },
  { word: 'Jumanji', clue: 'Board Game Jungle' },
  { word: 'Home Alone', clue: 'Kid Defends House' },
  { word: 'The Breakfast Club', clue: 'Saturday Detention Teens' },
  { word: 'Mean Girls', clue: 'High School Cliques' },
  { word: 'Clueless', clue: 'Beverly Hills Teen Makeover' },
  { word: '10 Things I Hate About You', clue: 'Taming of Shrew Teen' },
  { word: 'The Notebook', clue: 'Alzheimer Love Letters' },
  { word: 'La La Land', clue: 'Jazz Actress Musical' },
  { word: 'Moulin Rouge', clue: 'Paris Cabaret Love' },
  { word: 'The Greatest Showman', clue: 'Barnum Circus Musical' },
  { word: 'Bohemian Rhapsody', clue: 'Freddie Mercury Queen' },
  { word: 'Rocketman', clue: 'Elton John Fantasy' },
  { word: 'A Star is Born', clue: 'Musician Discovers Singer' },
  { word: 'Chicago', clue: 'Murder Jazz Musical' },
  { word: 'Grease', clue: '50s High School Musical' },
  { word: 'The Sound of Music', clue: 'Von Trapp Family Hills' },
  { word: 'West Side Story', clue: 'Romeo Juliet Gangs' },
  { word: 'Casablanca', clue: 'Play It Again Sam' },
  { word: 'Gone with the Wind', clue: 'Civil War Southern Belle' },
  { word: 'Citizen Kane', clue: 'Newspaper Tycoon Rosebud' },
  { word: '2001 Space Odyssey', clue: 'Kubrick Monolith AI' },
  { word: 'Apocalypse Now', clue: 'Vietnam War Madness' },
  { word: 'Full Metal Jacket', clue: 'Marine Boot Camp War' },
  { word: 'Platoon', clue: 'Vietnam Ground Combat' },
  { word: 'Black Hawk Down', clue: 'Somalia Helicopter Mission' },
  { word: 'Dunkirk', clue: 'WWII Beach Evacuation' },
  { word: '1917', clue: 'WWI One Shot Mission' },
  { word: 'Hacksaw Ridge', clue: 'Medic No Gun Hero' },
  { word: 'American Sniper', clue: 'Navy SEAL Marksman' },
  { word: 'Lone Survivor', clue: 'Afghanistan SEAL Mission' },
  { word: 'Zero Dark Thirty', clue: 'Bin Laden Hunt' },
  { word: 'Argo', clue: 'Iran Hostage Fake Movie' },
  { word: 'Captain Phillips', clue: 'Somali Pirate Hijack' },
  { word: 'Sully', clue: 'Hudson River Landing' },
  { word: 'Apollo 13', clue: 'Houston We Have Problem' },
  { word: 'The Martian', clue: 'Stranded Mars Potatoes' },
  { word: 'Gravity', clue: 'Space Station Disaster' },
  { word: 'The Revenant', clue: 'Bear Mauling Survival' },
  { word: '127 Hours', clue: 'Arm Trapped Boulder' },
  { word: 'Cast Away', clue: 'Island Volleyball Wilson' },
  { word: 'Into the Wild', clue: 'Alaska Wilderness Journey' },
  { word: 'Wild', clue: 'PCT Trail Hike Memoir' },
  { word: 'Everest', clue: 'Mountain Climbing Disaster' },
  { word: 'The Imitation Game', clue: 'Turing Enigma Code' },
  { word: 'A Beautiful Mind', clue: 'Mathematician Schizophrenia' },
  { word: 'The Theory of Everything', clue: 'Stephen Hawking Biopic' },
  { word: 'The King\'s Speech', clue: 'Stutter Royal Therapy' },
  { word: 'Lincoln', clue: 'Spielberg President Abolition' },
  { word: 'Gandhi', clue: 'Indian Independence Leader' },
  { word: 'Malcolm X', clue: 'Civil Rights Leader' },
  { word: 'Selma', clue: 'MLK Voting Rights March' },
  { word: '12 Years a Slave', clue: 'Kidnapped Free Man' },
  { word: 'Django Unchained', clue: 'Freed Slave Bounty Hunter' },
  { word: 'Inglourious Basterds', clue: 'Nazi Hunting Soldiers' },
];
