export const kpopCelebrities = [
  // BTS Members
  { word: 'BTS', clue: 'Korean Boy Band Global' },
  { word: 'RM', clue: 'BTS Leader Rapper' },
  { word: 'Jin', clue: 'BTS Eldest Visual' },
  { word: 'Suga', clue: 'BTS Rapper Producer' },
  { word: 'J-Hope', clue: 'BTS Sunshine Dancer' },
  { word: 'Jimin', clue: 'BTS Main Dancer' },
  { word: 'V', clue: 'BTS Deep Voice Actor' },
  { word: 'Jungkook', clue: 'BTS Golden Maknae' },
  
  // BLACKPINK Members
  { word: 'BLACKPINK', clue: 'Korean Girl Group' },
  { word: 'Jennie', clue: 'BLACKPINK Main Rapper' },
  { word: 'Jisoo', clue: 'BLACKPINK Visual Actress' },
  { word: 'Rosé', clue: 'BLACKPINK Main Vocalist' },
  { word: 'Lisa', clue: 'BLACKPINK Thai Dancer' },
  
  // TWICE Members
  { word: 'TWICE', clue: 'Once Fandom Girl Group' },
  { word: 'Nayeon', clue: 'TWICE Center Rabbit' },
  { word: 'Jeongyeon', clue: 'TWICE Short Hair Lead' },
  { word: 'Momo', clue: 'TWICE Japanese Dancer' },
  { word: 'Sana', clue: 'TWICE Shy Shy Shy' },
  { word: 'Jihyo', clue: 'TWICE Leader Vocalist' },
  { word: 'Mina', clue: 'TWICE Elegant Ballet' },
  { word: 'Dahyun', clue: 'TWICE Eagle Dance' },
  { word: 'Chaeyoung', clue: 'TWICE Rapper Artist' },
  { word: 'Tzuyu', clue: 'TWICE Taiwanese Maknae' },
  
  // EXO Members
  { word: 'EXO', clue: 'SM Boy Group Powers' },
  { word: 'Suho', clue: 'EXO Leader Rich Voice' },
  { word: 'Xiumin', clue: 'EXO Eldest Frost' },
  { word: 'Lay', clue: 'EXO Chinese Unicorn' },
  { word: 'Baekhyun', clue: 'EXO Light Vocalist' },
  { word: 'Chen', clue: 'EXO Lightning Main Vocal' },
  { word: 'Chanyeol', clue: 'EXO Fire Rapper' },
  { word: 'D.O.', clue: 'EXO Earth Actor' },
  { word: 'Kai', clue: 'EXO Teleport Dancer' },
  { word: 'Sehun', clue: 'EXO Wind Maknae' },
  
  // Other Popular Groups
  { word: 'Stray Kids', clue: 'JYP Self Producing Group' },
  { word: 'Bang Chan', clue: 'Stray Kids Leader Producer' },
  { word: 'Felix', clue: 'Stray Kids Deep Voice' },
  { word: 'Hyunjin', clue: 'Stray Kids Dancer Visual' },
  { word: 'SEVENTEEN', clue: '13 Members Self Producing' },
  { word: 'NCT', clue: 'Unlimited Members Concept' },
  { word: 'Red Velvet', clue: 'Dual Concept Girl Group' },
  { word: 'Irene', clue: 'Red Velvet Leader Visual' },
  { word: 'Seulgi', clue: 'Red Velvet Bear Dancer' },
  { word: 'Wendy', clue: 'Red Velvet Main Vocal' },
  { word: 'Joy', clue: 'Red Velvet Actress Cheerful' },
  { word: 'Yeri', clue: 'Red Velvet Maknae' },
  { word: 'ITZY', clue: 'Girl Crush Teen Group' },
  { word: 'Yeji', clue: 'ITZY Leader Cat Eyes' },
  { word: 'Lia', clue: 'ITZY Main Vocal' },
  { word: 'Ryujin', clue: 'ITZY Rapper Center' },
  { word: 'Chaeryeong', clue: 'ITZY Main Dancer' },
  { word: 'Yuna', clue: 'ITZY Tall Maknae' },
  { word: 'aespa', clue: 'AI Avatar Girl Group' },
  { word: 'Karina', clue: 'aespa Leader Visual' },
  { word: 'Giselle', clue: 'aespa Japanese Rapper' },
  { word: 'Winter', clue: 'aespa Main Vocalist' },
  { word: 'Ningning', clue: 'aespa Chinese Vocal' },
  { word: 'NewJeans', clue: 'Y2K Teen Girl Group' },
  { word: 'LE SSERAFIM', clue: 'Fearless Girl Group' },
  { word: 'IVE', clue: 'I Have Girl Group' },
  { word: 'TXT', clue: 'Tomorrow X Together BigHit' },
  { word: 'ENHYPEN', clue: 'Vampire Concept Boy Group' },
  { word: 'ATEEZ', clue: 'Pirate Concept Performance' },
  { word: 'The Boyz', clue: 'Road to Kingdom Winners' },
  { word: 'Monsta X', clue: 'Powerful Performance Group' },
  { word: 'GOT7', clue: 'Bird Fandom Boy Group' },
  { word: 'MAMAMOO', clue: 'Vocal Powerhouse Girls' },
  { word: '(G)I-DLE', clue: 'Self Producing Girl Group' },
  { word: 'EVERGLOW', clue: 'Global Girl Group' },
  { word: 'NMIXX', clue: 'Mix Pop Experimental' },
  { word: 'Kep1er', clue: 'Girls Planet Survival Group' },
  
  // Solo Artists
  { word: 'IU', clue: 'Nation\'s Little Sister' },
  { word: 'Taeyeon', clue: 'SNSD Leader Solo' },
  { word: 'PSY', clue: 'Gangnam Style Viral' },
  { word: 'HyunA', clue: 'Sexy Concept Solo' },
  { word: 'Sunmi', clue: 'Gashina Wonder Girls' },
  { word: 'Chungha', clue: 'IOI Solo Dancer' },
  { word: 'Taemin', clue: 'SHINee Solo King' },
  { word: 'G-Dragon', clue: 'BIGBANG Fashion Icon' },
  { word: 'Jay Park', clue: 'Korean American AOMG' },
  { word: 'CL', clue: '2NE1 Leader Badass' },
  { word: 'Zico', clue: 'Block B Rapper Producer' },
  { word: 'Hwasa', clue: 'MAMAMOO Solo Powerful' },
  { word: 'Crush', clue: 'R&B Vocalist' },
  { word: 'Dean', clue: 'Alternative R&B' },
  
  // Actors/Actresses
  { word: 'Lee Min Ho', clue: 'Boys Over Flowers Actor' },
  { word: 'Song Joong Ki', clue: 'Descendants of Sun Actor' },
  { word: 'Park Seo Joon', clue: 'Itaewon Class Actor' },
  { word: 'Kim Soo Hyun', clue: 'My Love from Star' },
  { word: 'Hyun Bin', clue: 'Crash Landing Actor' },
  { word: 'Lee Jong Suk', clue: 'W Two Worlds Actor' },
  { word: 'Park Bo Gum', clue: 'Reply 1988 Actor' },
  { word: 'Song Hye Kyo', clue: 'Descendants Actress' },
  { word: 'Jun Ji Hyun', clue: 'My Sassy Girl Actress' },
  { word: 'IU', clue: 'Hotel Del Luna Actress' },
  { word: 'Suzy', clue: 'Miss A Actress Nation First Love' },
  { word: 'Park Shin Hye', clue: 'Heirs Actress' },
];
