export const movies = [
  // Iconic Movies
  { word: 'Titanic', clue: 'Ship Disaster Romance' },
  { word: 'Avatar', clue: 'Blue Aliens Planet' },
  { word: 'The Godfather', clue: 'Mafia Family Classic' },
  { word: 'Inception', clue: 'Dream Heist Film' },
  { word: 'The Matrix', clue: 'Red Pill Blue Pill' },
  { word: 'Interstellar', clue: 'Space Time Travel' },
  { word: 'The Dark Knight', clue: 'Batman vs Joker' },
  { word: 'Pulp Fiction', clue: 'Quentin Tarantino Crime' },
  { word: 'Fight Club', clue: 'Underground Boxing' },
  { word: 'Forrest Gump', clue: 'Running Across America' },
  { word: 'The Shawshank Redemption', clue: 'Prison Escape Story' },
  { word: 'Jurassic Park', clue: 'Dinosaur Theme Park' },
  { word: 'Star Wars', clue: 'Space Saga Epic' },
  { word: 'The Lord of the Rings', clue: 'Fantasy Quest Adventure' },
  { word: 'Harry Potter', clue: 'Wizard School Magic' },
  { word: 'Avengers', clue: 'Marvel Superhero Team' },
  { word: 'Spider-Man', clue: 'Web Slinging Hero' },
  { word: 'Iron Man', clue: 'Genius Billionaire Suit' },
  { word: 'The Lion King', clue: 'African Pride Lands' },
  { word: 'Toy Story', clue: 'Animated Toys Adventure' },
  { word: 'Finding Nemo', clue: 'Lost Clownfish Journey' },
  { word: 'Frozen', clue: 'Ice Queen Sister' },
  { word: 'The Terminator', clue: 'Robot Time Traveler' },
  { word: 'Jurassic World', clue: 'Modern Dinosaur Park' },
  { word: 'Gladiator', clue: 'Roman Arena Fighter' },
  { word: 'The Silence of the Lambs', clue: 'Cannibal Serial Killer' },
  { word: 'Schindler\'s List', clue: 'Holocaust Survivor Story' },
  { word: 'The Green Mile', clue: 'Death Row Miracle' },
  { word: 'Saving Private Ryan', clue: 'World War 2 Mission' },
  { word: 'The Departed', clue: 'Police Undercover Mob' },
  { word: 'Good Will Hunting', clue: 'Genius Janitor Math' },
  { word: 'The Prestige', clue: 'Magician Rivalry' },
  { word: 'Memento', clue: 'Backward Memory Loss' },
  { word: 'Shutter Island', clue: 'Asylum Mystery Twist' },
  { word: 'The Sixth Sense', clue: 'I See Dead People' },
  { word: 'The Usual Suspects', clue: 'Crime Thriller Twist' },
  { word: 'Seven', clue: 'Seven Deadly Sins' },
  { word: 'The Truman Show', clue: 'Reality TV Life' },
  { word: 'Eternal Sunshine', clue: 'Memory Erasing Romance' },
  { word: 'The Social Network', clue: 'Facebook Origin Story' },
  { word: 'Whiplash', clue: 'Jazz Drummer Teacher' },
  { word: 'La La Land', clue: 'Musical Romance Hollywood' },
  { word: 'Parasite', clue: 'Korean Class Thriller' },
  { word: 'Joker', clue: 'Villain Origin Story' },
  { word: 'Dunkirk', clue: 'War Evacuation Beach' },
  { word: 'Oppenheimer', clue: 'Atomic Bomb Creator' },
  { word: 'Barbie', clue: 'Pink Plastic Doll' },
  { word: 'Top Gun', clue: 'Fighter Pilot Training' },
  { word: 'Mission Impossible', clue: 'Spy Action Stunts' },
  { word: 'Fast and Furious', clue: 'Street Racing Family' },
  { word: 'Pirates of the Caribbean', clue: 'Captain Jack Sparrow' },
  { word: 'The Hunger Games', clue: 'Dystopian Battle Royale' },
  { word: 'Twilight', clue: 'Vampire Love Triangle' },
  { word: 'The Notebook', clue: 'Rainy Kiss Romance' },
  { word: 'Titanic', clue: 'Sinking Ship Love' },
  { word: 'Slumdog Millionaire', clue: 'Indian Game Show' },
  { word: 'Life of Pi', clue: 'Boy Tiger Boat' },
  { word: 'Gravity', clue: 'Space Debris Disaster' },
  { word: 'The Revenant', clue: 'Bear Attack Survival' },
  { word: 'Mad Max', clue: 'Post Apocalyptic Desert' },
  { word: 'Black Panther', clue: 'Wakanda African Hero' },
  { word: 'Wonder Woman', clue: 'Amazon Warrior Princess' },
  { word: 'Aquaman', clue: 'Underwater Atlantis King' },
  { word: 'Deadpool', clue: 'Fourth Wall Breaking Merc' },
  { word: 'Logan', clue: 'Old Wolverine Western' },
  { word: 'Guardians of the Galaxy', clue: 'Space Outlaws Team' },
  { word: 'Doctor Strange', clue: 'Mystic Arts Sorcerer' },
  { word: 'Ant-Man', clue: 'Shrinking Superhero' },
  { word: 'Captain America', clue: 'Super Soldier Shield' },
  { word: 'Thor', clue: 'Norse God Hammer' },
  { word: 'Black Widow', clue: 'Russian Spy Assassin' },
  { word: 'The Hobbit', clue: 'Bilbo Baggins Adventure' },
  { word: 'The Chronicles of Narnia', clue: 'Wardrobe Magic World' },
  { word: 'Fantastic Beasts', clue: 'Wizard Creatures Hunt' },
  { word: 'The Greatest Showman', clue: 'Circus Musical Biography' },
  { word: 'Bohemian Rhapsody', clue: 'Queen Band Biopic' },
  { word: 'Rocketman', clue: 'Elton John Musical' },
  { word: 'A Star is Born', clue: 'Singer Discovery Romance' },
  { word: 'Coco', clue: 'Mexican Day of Dead' },
  { word: 'Moana', clue: 'Polynesian Ocean Adventure' },
  { word: 'Zootopia', clue: 'Animal City Detective' },
  { word: 'Inside Out', clue: 'Emotions in Mind' },
  { word: 'Up', clue: 'Flying House Balloons' },
  { word: 'WALL-E', clue: 'Robot Trash Earth' },
  { word: 'Ratatouille', clue: 'Cooking Rat Paris' },
  { word: 'Monsters Inc', clue: 'Scaring Kids Factory' },
  { word: 'The Incredibles', clue: 'Superhero Family' },
  { word: 'Cars', clue: 'Racing Vehicles World' },
  { word: 'Shrek', clue: 'Ogre Fairy Tale' },
  { word: 'Kung Fu Panda', clue: 'Martial Arts Bear' },
  { word: 'How to Train Your Dragon', clue: 'Viking Boy Dragon' },
  { word: 'Despicable Me', clue: 'Villain Minions Adoption' },
  { word: 'The Lego Movie', clue: 'Animated Building Blocks' },
  { word: 'Minions', clue: 'Yellow Pill Creatures' },
];
