export interface WordPair {
  word: string;
  clue: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export const objects: WordPair[] = [
  { word: 'Chair', clue: 'Stool', difficulty: 'easy' },
  { word: 'Laptop', clue: 'Tablet', difficulty: 'easy' },
  { word: 'Guitar', clue: 'Bass', difficulty: 'medium' },
  { word: 'Piano', clue: 'Keyboard', difficulty: 'easy' },
  { word: 'Knife', clue: 'Fork', difficulty: 'easy' },
  { word: 'Spoon', clue: 'Ladle', difficulty: 'medium' },
  { word: 'Pencil', clue: 'Pen', difficulty: 'easy' },
  { word: 'Book', clue: 'Magazine', difficulty: 'easy' },
  { word: 'Clock', clue: 'Watch', difficulty: 'easy' },
  { word: 'Mirror', clue: 'Glass', difficulty: 'medium' },
  { word: 'Lamp', clue: 'Chandelier', difficulty: 'medium' },
  { word: 'Sofa', clue: 'Couch', difficulty: 'hard' },
  { word: 'Pillow', clue: 'Cushion', difficulty: 'hard' },
  { word: 'Blanket', clue: 'Quilt', difficulty: 'hard' },
  { word: 'Umbrella', clue: 'Parasol', difficulty: 'hard' },
  { word: 'Backpack', clue: 'Suitcase', difficulty: 'medium' },
  { word: 'Scissors', clue: 'Shears', difficulty: 'hard' },
  { word: 'Hammer', clue: 'Mallet', difficulty: 'hard' },
  { word: 'Screwdriver', clue: 'Wrench', difficulty: 'medium' },
  { word: 'Saw', clue: 'Blade', difficulty: 'medium' },
  { word: 'Microwave', clue: 'Oven', difficulty: 'easy' },
  { word: 'Refrigerator', clue: 'Freezer', difficulty: 'medium' },
  { word: 'Blender', clue: 'Mixer', difficulty: 'hard' },
  { word: 'Toaster', clue: 'Grill', difficulty: 'medium' },
  { word: 'Camera', clue: 'Camcorder', difficulty: 'medium' },
  { word: 'Television', clue: 'Monitor', difficulty: 'easy' },
  { word: 'Radio', clue: 'Speaker', difficulty: 'medium' },
  { word: 'Headphones', clue: 'Earbuds', difficulty: 'medium' },
  { word: 'Mousepad', clue: 'Coaster', difficulty: 'hard' },
  { word: 'Keyboard', clue: 'Piano', difficulty: 'hard' },
  { word: 'Stapler', clue: 'Hole Punch', difficulty: 'medium' },
  { word: 'Ruler', clue: 'Measuring Tape', difficulty: 'medium' },
  { word: 'Eraser', clue: 'Whiteout', difficulty: 'hard' },
  { word: 'Paintbrush', clue: 'Marker', difficulty: 'medium' },
  { word: 'Canvas', clue: 'Paper', difficulty: 'medium' },
  { word: 'Wheelbarrow', clue: 'Cart', difficulty: 'medium' },
  { word: 'Shovel', clue: 'Spade', difficulty: 'hard' },
  { word: 'Rake', clue: 'Broom', difficulty: 'medium' },
  { word: 'Hose', clue: 'Sprinkler', difficulty: 'medium' },
  { word: 'Flashlight', clue: 'Lantern', difficulty: 'medium' },
  { word: 'Candle', clue: 'Torch', difficulty: 'medium' },
  { word: 'Vase', clue: 'Pot', difficulty: 'medium' },
  { word: 'Kettle', clue: 'Teapot', difficulty: 'hard' },
  { word: 'Mop', clue: 'Broom', difficulty: 'medium' },
  { word: 'Bucket', clue: 'Pail', difficulty: 'hard' },
  { word: 'Basket', clue: 'Bin', difficulty: 'medium' },
  { word: 'Trophy', clue: 'Medal', difficulty: 'easy' },
  { word: 'Globe', clue: 'Map', difficulty: 'easy' },
  { word: 'Calendar', clue: 'Planner', difficulty: 'medium' },
  { word: 'Telescope', clue: 'Binoculars', difficulty: 'easy' },
];
