export interface WordPair {
  word: string;
  clue: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export const sports: WordPair[] = [
  { word: 'Soccer', clue: 'Football', difficulty: 'hard' },
  { word: 'Basketball', clue: 'Volleyball', difficulty: 'easy' },
  { word: 'Tennis', clue: 'Badminton', difficulty: 'easy' },
  { word: 'Baseball', clue: 'Cricket', difficulty: 'medium' },
  { word: 'Swimming', clue: 'Diving', difficulty: 'easy' },
  { word: 'Boxing', clue: 'MMA', difficulty: 'easy' },
  { word: 'Hockey', clue: 'Lacrosse', difficulty: 'medium' },
  { word: 'Golf', clue: 'Mini Golf', difficulty: 'easy' },
  { word: 'Skiing', clue: 'Snowboarding', difficulty: 'easy' },
  { word: 'Surfing', clue: 'Wakeboarding', difficulty: 'medium' },
  { word: 'Wrestling', clue: 'Judo', difficulty: 'medium' },
  { word: 'Karate', clue: 'Taekwondo', difficulty: 'hard' },
  { word: 'Running', clue: 'Jogging', difficulty: 'hard' },
  { word: 'Marathon', clue: 'Sprint', difficulty: 'easy' },
  { word: 'Cycling', clue: 'Mountain Biking', difficulty: 'medium' },
  { word: 'Gymnastics', clue: 'Acrobatics', difficulty: 'hard' },
  { word: 'Figure Skating', clue: 'Ice Dancing', difficulty: 'hard' },
  { word: 'Skateboarding', clue: 'Longboarding', difficulty: 'medium' },
  { word: 'Rock Climbing', clue: 'Bouldering', difficulty: 'hard' },
  { word: 'Archery', clue: 'Darts', difficulty: 'medium' },
  { word: 'Fencing', clue: 'Sword Fighting', difficulty: 'hard' },
  { word: 'Rowing', clue: 'Kayaking', difficulty: 'medium' },
  { word: 'Sailing', clue: 'Yachting', difficulty: 'hard' },
  { word: 'Horseback Riding', clue: 'Polo', difficulty: 'medium' },
  { word: 'Polo', clue: 'Water Polo', difficulty: 'hard' },
  { word: 'Cheerleading', clue: 'Dance', difficulty: 'medium' },
  { word: 'Parkour', clue: 'Free Running', difficulty: 'hard' },
  { word: 'Triathlon', clue: 'Decathlon', difficulty: 'hard' },
  { word: 'Bowling', clue: 'Ten Pin', difficulty: 'hard' },
  { word: 'Billiards', clue: 'Pool', difficulty: 'hard' },
  { word: 'Ping Pong', clue: 'Table Tennis', difficulty: 'hard' },
  { word: 'Rugby', clue: 'American Football', difficulty: 'easy' },
  { word: 'Handball', clue: 'Water Polo', difficulty: 'hard' },
  { word: 'Squash', clue: 'Racquetball', difficulty: 'hard' },
  { word: 'Curling', clue: 'Bowling on Ice', difficulty: 'hard' },
  { word: 'Bobsled', clue: 'Luge', difficulty: 'hard' },
  { word: 'Speed Skating', clue: 'Figure Skating', difficulty: 'medium' },
  { word: 'Weightlifting', clue: 'Powerlifting', difficulty: 'hard' },
  { word: 'Crossfit', clue: 'Bodybuilding', difficulty: 'medium' },
  { word: 'Yoga', clue: 'Pilates', difficulty: 'medium' },
  { word: 'Kickboxing', clue: 'Boxing', difficulty: 'easy' },
  { word: 'Sumo Wrestling', clue: 'Wrestling', difficulty: 'easy' },
  { word: 'Tai Chi', clue: 'Kung Fu', difficulty: 'hard' },
  { word: 'Dodgeball', clue: 'Kickball', difficulty: 'medium' },
  { word: 'Ultimate Frisbee', clue: 'Disc Golf', difficulty: 'medium' },
  { word: 'Softball', clue: 'Baseball', difficulty: 'medium' },
  { word: 'Field Hockey', clue: 'Ice Hockey', difficulty: 'easy' },
  { word: 'Beach Volleyball', clue: 'Volleyball', difficulty: 'easy' },
  { word: 'BMX', clue: 'Motocross', difficulty: 'easy' },
  { word: 'Formula 1', clue: 'NASCAR', difficulty: 'easy' },
];
