export const superheroes = [
  // Marvel Heroes
  { word: 'Spider-Man', clue: 'Web Slinging Wall Crawler' },
  { word: 'Iron Man', clue: 'Genius Billionaire Suit' },
  { word: 'Captain America', clue: 'Super Soldier Shield' },
  { word: 'Thor', clue: 'Norse God Hammer' },
  { word: 'Hulk', clue: 'Green Rage Monster' },
  { word: 'Black Widow', clue: 'Russian Spy Assassin' },
  { word: 'Hawkeye', clue: 'Master Archer Agent' },
  { word: 'Black Panther', clue: 'Wakanda Vibranium King' },
  { word: 'Doctor Strange', clue: 'Mystic Arts Sorcerer' },
  { word: 'Scarlet Witch', clue: 'Reality Warping Witch' },
  { word: 'Vision', clue: 'Mind Stone Android' },
  { word: 'Ant-Man', clue: 'Shrinking Size Hero' },
  { word: 'Wasp', clue: 'Flying Shrinking Woman' },
  { word: 'Captain Marvel', clue: 'Cosmic Energy Woman' },
  { word: 'Star-Lord', clue: 'Guardian Spaceship Leader' },
  { word: 'Gamora', clue: 'Green Assassin Daughter' },
  { word: 'Drax', clue: 'Destroyer Literal Warrior' },
  { word: 'Rocket', clue: 'Genetically Modified Raccoon' },
  { word: 'Groot', clue: 'I Am Tree' },
  { word: 'Wolverine', clue: 'Metal Claws Healing' },
  { word: 'Cyclops', clue: 'Laser Eye Beam' },
  { word: 'Storm', clue: 'Weather Control Mutant' },
  { word: 'Jean Grey', clue: 'Phoenix Telepathic Mutant' },
  { word: 'Professor X', clue: 'Bald Telepathic Wheelchair' },
  { word: 'Magneto', clue: 'Metal Controlling Villain' },
  { word: 'Deadpool', clue: 'Fourth Wall Regenerating Merc' },
  { word: 'Daredevil', clue: 'Blind Hell\'s Kitchen Lawyer' },
  { word: 'Luke Cage', clue: 'Unbreakable Skin Hero' },
  { word: 'Jessica Jones', clue: 'Super Strong Detective' },
  { word: 'Iron Fist', clue: 'Glowing Fist Martial Artist' },
  { word: 'Punisher', clue: 'Skull Vigilante Veteran' },
  { word: 'Ghost Rider', clue: 'Flaming Skull Motorcycle' },
  { word: 'Moon Knight', clue: 'Multiple Personality Mercenary' },
  { word: 'She-Hulk', clue: 'Green Lawyer Cousin' },
  { word: 'Ms. Marvel', clue: 'Stretchy Pakistani Teen' },
  { word: 'Shang-Chi', clue: 'Martial Arts Ten Rings' },
  { word: 'Blade', clue: 'Vampire Hunter Daywalker' },
  { word: 'Loki', clue: 'Trickster God Brother' },
  { word: 'Thanos', clue: 'Purple Infinity Gauntlet' },
  { word: 'Venom', clue: 'Black Symbiote Alien' },
  { word: 'Carnage', clue: 'Red Symbiote Psycho' },
  
  // DC Heroes
  { word: 'Superman', clue: 'Man of Steel Krypton' },
  { word: 'Batman', clue: 'Dark Knight Gotham' },
  { word: 'Wonder Woman', clue: 'Amazon Warrior Princess' },
  { word: 'The Flash', clue: 'Fastest Man Alive' },
  { word: 'Aquaman', clue: 'Atlantis Ocean King' },
  { word: 'Green Lantern', clue: 'Willpower Ring Corps' },
  { word: 'Cyborg', clue: 'Half Machine Teen' },
  { word: 'Shazam', clue: 'Magic Word Kid Hero' },
  { word: 'Green Arrow', clue: 'Billionaire Archer Vigilante' },
  { word: 'Supergirl', clue: 'Superman\'s Cousin' },
  { word: 'Batgirl', clue: 'Batman\'s Protege' },
  { word: 'Robin', clue: 'Batman\'s Sidekick' },
  { word: 'Nightwing', clue: 'Former Robin Adult' },
  { word: 'Red Hood', clue: 'Resurrected Robin Antihero' },
  { word: 'Harley Quinn', clue: 'Joker\'s Girlfriend Clown' },
  { word: 'Catwoman', clue: 'Feline Thief Love Interest' },
  { word: 'Poison Ivy', clue: 'Plant Controlling Villain' },
  { word: 'The Joker', clue: 'Clown Criminal Mastermind' },
  { word: 'Lex Luthor', clue: 'Bald Billionaire Villain' },
  { word: 'Darkseid', clue: 'Apokolips Omega Beams' },
  { word: 'Deathstroke', clue: 'Mercenary Assassin Villain' },
  { word: 'Reverse Flash', clue: 'Yellow Speedster Villain' },
  { word: 'Sinestro', clue: 'Yellow Lantern Fear' },
  { word: 'Black Adam', clue: 'Ancient Shazam Villain' },
  { word: 'Peacemaker', clue: 'Peace At Any Cost' },
  { word: 'Blue Beetle', clue: 'Alien Scarab Armor' },
  { word: 'Static Shock', clue: 'Electricity Controlling Teen' },
  { word: 'Raven', clue: 'Demon Daughter Empath' },
  { word: 'Beast Boy', clue: 'Green Shapeshifting Teen' },
  { word: 'Starfire', clue: 'Alien Princess Energy Blasts' },
  { word: 'Constantine', clue: 'Occult Detective Smoker' },
  
  // Other Heroes
  { word: 'The Incredibles', clue: 'Superhero Family Movie' },
  { word: 'Mr. Incredible', clue: 'Super Strength Father' },
  { word: 'Elastigirl', clue: 'Stretchy Mother Hero' },
  { word: 'Violet', clue: 'Invisible Force Field Teen' },
  { word: 'Dash', clue: 'Super Speed Boy' },
  { word: 'Jack-Jack', clue: 'Multi Power Baby' },
  { word: 'Frozone', clue: 'Ice Creating Friend' },
  { word: 'The Boys', clue: 'Anti Superhero Team' },
  { word: 'Homelander', clue: 'Evil Superman Parody' },
  { word: 'Starlight', clue: 'Light Powers Hero' },
  { word: 'Billy Butcher', clue: 'Superhero Hating Leader' },
  { word: 'Invincible', clue: 'Viltrumite Teen Hero' },
  { word: 'Omni-Man', clue: 'Superman Like Father' },
  { word: 'Spawn', clue: 'Hell Resurrected Antihero' },
  { word: 'Hellboy', clue: 'Red Demon Investigator' },
  { word: 'The Tick', clue: 'Blue Spoon Hero' },
  { word: 'One Punch Man', clue: 'Bald Unbeatable Hero' },
  { word: 'All Might', clue: 'Symbol of Peace Hero' },
  { word: 'Deku', clue: 'Quirkless Inheritor Hero' },
];
