export const tvShows = [
  // Popular TV Shows
  { word: 'Breaking Bad', clue: 'Chemistry Teacher Drug Lord' },
  { word: 'Game of Thrones', clue: 'Fantasy Dragon Throne' },
  { word: 'Stranger Things', clue: 'Upside Down 80s Kids' },
  { word: 'The Office', clue: 'Paper Company Mockumentary' },
  { word: 'Friends', clue: 'Six New York Friends' },
  { word: 'The Big Bang Theory', clue: 'Nerdy Physicists Sitcom' },
  { word: 'Sherlock', clue: 'Modern Detective London' },
  { word: 'Peaky Blinders', clue: 'British Gangster Family' },
  { word: 'The Crown', clue: 'British Royal Family' },
  { word: 'The Mandalorian', clue: 'Baby Yoda Bounty Hunter' },
  { word: 'The Witcher', clue: 'Monster Hunter Sorcery' },
  { word: 'Wednesday', clue: 'Addams Family Daughter' },
  { word: 'Squid Game', clue: 'Korean Deadly Games' },
  { word: 'Money Heist', clue: 'Spanish Bank Robbery' },
  { word: 'Narcos', clue: 'Colombian Drug Cartel' },
  { word: 'The Walking Dead', clue: 'Zombie Apocalypse Survival' },
  { word: 'Westworld', clue: 'Robot Theme Park' },
  { word: 'Black Mirror', clue: 'Tech Dystopia Anthology' },
  { word: 'The Boys', clue: 'Evil Superheroes' },
  { word: 'The Umbrella Academy', clue: 'Dysfunctional Superhero Family' },
  { word: 'Lucifer', clue: 'Devil Crime Detective' },
  { word: 'The Flash', clue: 'Speedster Superhero' },
  { word: 'Arrow', clue: 'Green Hood Vigilante' },
  { word: 'Supernatural', clue: 'Monster Hunting Brothers' },
  { word: 'Vikings', clue: 'Norse Warriors Saga' },
  { word: 'The Last of Us', clue: 'Fungal Zombie Apocalypse' },
  { word: 'House of the Dragon', clue: 'Targaryen Family War' },
  { word: 'The Handmaid\'s Tale', clue: 'Dystopian Women Slavery' },
  { word: 'Ozark', clue: 'Money Laundering Family' },
  { word: 'Better Call Saul', clue: 'Breaking Bad Lawyer' },
  { word: 'Succession', clue: 'Media Dynasty Family' },
  { word: 'The Wire', clue: 'Baltimore Crime Drama' },
  { word: 'True Detective', clue: 'Dark Crime Anthology' },
  { word: 'Fargo', clue: 'Crime Black Comedy' },
  { word: 'Chernobyl', clue: 'Nuclear Disaster Mini' },
  { word: 'Band of Brothers', clue: 'WW2 Paratroopers' },
  { word: 'The Sopranos', clue: 'Italian Mob Boss' },
  { word: 'Mad Men', clue: '60s Advertising Agency' },
  { word: 'Lost', clue: 'Mysterious Island Crash' },
  { word: 'Prison Break', clue: 'Escape Conspiracy Plan' },
  { word: 'How I Met Your Mother', clue: 'Ted Future Story' },
  { word: 'Modern Family', clue: 'Three Family Mockumentary' },
  { word: 'Brooklyn Nine-Nine', clue: 'Comedy Police Precinct' },
  { word: 'Parks and Recreation', clue: 'Government Department Comedy' },
  { word: 'The Good Place', clue: 'Afterlife Philosophy Comedy' },
  { word: 'Rick and Morty', clue: 'Scientist Grandson Adventures' },
  { word: 'South Park', clue: 'Colorado Kids Satire' },
  { word: 'Family Guy', clue: 'Griffin Family Cutaways' },
  { word: 'The Simpsons', clue: 'Yellow Springfield Family' },
  { word: 'Suits', clue: 'Law Firm Harvey Mike' },
  { word: 'Grey\'s Anatomy', clue: 'Seattle Hospital Surgeons' },
  { word: 'House', clue: 'Brilliant Diagnostic Doctor' },
  { word: 'Scrubs', clue: 'Medical Comedy Hospital' },
  { word: 'The Good Doctor', clue: 'Autistic Surgeon Genius' },
  { word: 'ER', clue: 'Emergency Room Drama' },
  { word: 'Dexter', clue: 'Serial Killer Blood Analyst' },
  { word: 'Hannibal', clue: 'Cannibal Psychiatrist' },
  { word: 'Mindhunter', clue: 'FBI Serial Killer Profiler' },
  { word: 'Criminal Minds', clue: 'FBI Behavioral Analysis' },
  { word: 'CSI', clue: 'Crime Scene Investigation' },
  { word: 'NCIS', clue: 'Naval Criminal Investigators' },
  { word: 'Law & Order', clue: 'Police Courtroom Drama' },
  { word: 'The Blacklist', clue: 'Criminal Informant FBI' },
  { word: 'Homeland', clue: 'CIA Bipolar Agent' },
  { word: '24', clue: 'Real Time Terror Threats' },
  { word: 'Jack Ryan', clue: 'CIA Analyst Action' },
  { word: 'The Marvelous Mrs. Maisel', clue: '50s Female Comedian' },
  { word: 'Fleabag', clue: 'Fourth Wall Breaking Woman' },
  { word: 'Killing Eve', clue: 'Agent Assassin Obsession' },
  { word: 'The Queen\'s Gambit', clue: 'Chess Prodigy Orphan' },
  { word: 'Bridgerton', clue: 'Regency Era Romance' },
  { word: 'Emily in Paris', clue: 'American Marketing Paris' },
  { word: 'Sex and the City', clue: 'Four NYC Women' },
  { word: 'Gossip Girl', clue: 'Upper East Side Teens' },
  { word: 'Pretty Little Liars', clue: 'Mystery A Stalker' },
  { word: 'Riverdale', clue: 'Dark Archie Comics' },
  { word: '13 Reasons Why', clue: 'Teen Suicide Tapes' },
  { word: 'Euphoria', clue: 'Teen Drug Drama' },
  { word: 'The Vampire Diaries', clue: 'Love Triangle Vampires' },
  { word: 'Teen Wolf', clue: 'High School Werewolf' },
  { word: 'Shadow and Bone', clue: 'Grisha Magic World' },
  { word: 'The 100', clue: 'Post Nuclear Survival' },
  { word: 'Cobra Kai', clue: 'Karate Kid Sequel' },
  { word: 'Outer Banks', clue: 'Treasure Hunt Teens' },
  { word: 'You', clue: 'Obsessive Stalker Killer' },
  { word: 'Dark', clue: 'German Time Travel Mystery' },
  { word: 'Alice in Borderland', clue: 'Japanese Death Games' },
  { word: 'Sweet Home', clue: 'Korean Monster Apartment' },
  { word: 'Kingdom', clue: 'Korean Zombie Historical' },
  { word: 'Crash Landing on You', clue: 'North South Korea Romance' },
];
