export interface WordPair {
  word: string;
  clue: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export const vehicles: WordPair[] = [
  { word: 'Car', clue: 'Automobile', difficulty: 'hard' },
  { word: 'Truck', clue: 'Pickup', difficulty: 'medium' },
  { word: 'SUV', clue: 'Jeep', difficulty: 'medium' },
  { word: 'Van', clue: 'Minivan', difficulty: 'hard' },
  { word: 'Motorcycle', clue: 'Scooter', difficulty: 'easy' },
  { word: 'Bicycle', clue: 'Bike', difficulty: 'hard' },
  { word: 'Bus', clue: 'Coach', difficulty: 'medium' },
  { word: 'Train', clue: 'Locomotive', difficulty: 'medium' },
  { word: 'Subway', clue: 'Metro', difficulty: 'hard' },
  { word: 'Tram', clue: 'Trolley', difficulty: 'hard' },
  { word: 'Airplane', clue: 'Jet', difficulty: 'easy' },
  { word: 'Helicopter', clue: 'Chopper', difficulty: 'medium' },
  { word: 'Glider', clue: 'Hang Glider', difficulty: 'hard' },
  { word: 'Hot Air Balloon', clue: 'Blimp', difficulty: 'medium' },
  { word: 'Boat', clue: 'Ship', difficulty: 'easy' },
  { word: 'Yacht', clue: 'Sailboat', difficulty: 'medium' },
  { word: 'Canoe', clue: 'Kayak', difficulty: 'medium' },
  { word: 'Jet Ski', clue: 'Speedboat', difficulty: 'medium' },
  { word: 'Cruise Ship', clue: 'Ferry', difficulty: 'easy' },
  { word: 'Submarine', clue: 'U-Boat', difficulty: 'hard' },
  { word: 'Tank', clue: 'Armored Vehicle', difficulty: 'medium' },
  { word: 'Ambulance', clue: 'Emergency Vehicle', difficulty: 'medium' },
  { word: 'Fire Truck', clue: 'Fire Engine', difficulty: 'hard' },
  { word: 'Police Car', clue: 'Patrol Car', difficulty: 'medium' },
  { word: 'Taxi', clue: 'Cab', difficulty: 'hard' },
  { word: 'Limousine', clue: 'Limo', difficulty: 'hard' },
  { word: 'Sports Car', clue: 'Race Car', difficulty: 'easy' },
  { word: 'Convertible', clue: 'Roadster', difficulty: 'hard' },
  { word: 'Coupe', clue: 'Sedan', difficulty: 'hard' },
  { word: 'Hatchback', clue: 'Compact Car', difficulty: 'hard' },
  { word: 'Electric Car', clue: 'Hybrid', difficulty: 'medium' },
  { word: 'Tesla', clue: 'Electric Vehicle', difficulty: 'easy' },
  { word: 'Tractor', clue: 'Farm Equipment', difficulty: 'medium' },
  { word: 'Bulldozer', clue: 'Excavator', difficulty: 'medium' },
  { word: 'Crane', clue: 'Lift', difficulty: 'medium' },
  { word: 'Forklift', clue: 'Pallet Jack', difficulty: 'hard' },
  { word: 'Dump Truck', clue: 'Garbage Truck', difficulty: 'medium' },
  { word: 'Cement Mixer', clue: 'Concrete Truck', difficulty: 'hard' },
  { word: 'Snowmobile', clue: 'ATV', difficulty: 'medium' },
  { word: 'Go-Kart', clue: 'Racing Kart', difficulty: 'medium' },
  { word: 'Segway', clue: 'Hoverboard', difficulty: 'easy' },
  { word: 'Skateboard', clue: 'Longboard', difficulty: 'medium' },
  { word: 'Roller Skates', clue: 'Rollerblades', difficulty: 'hard' },
  { word: 'Rickshaw', clue: 'Tuk-Tuk', difficulty: 'hard' },
  { word: 'Stagecoach', clue: 'Carriage', difficulty: 'medium' },
  { word: 'Golf Cart', clue: 'Utility Vehicle', difficulty: 'medium' },
  { word: 'Quad Bike', clue: 'Four Wheeler', difficulty: 'hard' },
  { word: 'Dirt Bike', clue: 'Motocross Bike', difficulty: 'medium' },
  { word: 'Chopper', clue: 'Cruiser Bike', difficulty: 'hard' },
  { word: 'Fighter Jet', clue: 'Military Plane', difficulty: 'easy' },
];
