export const videoGames = [
  // Popular Games
  { word: 'Minecraft', clue: 'Block Building Survival' },
  { word: 'Fortnite', clue: 'Battle Royale Building' },
  { word: 'Roblox', clue: 'User Created Games Platform' },
  { word: 'Among Us', clue: 'Impostor Spaceship Voting' },
  { word: 'PUBG', clue: 'Playerunknown Battlegrounds' },
  { word: 'Call of Duty', clue: 'Military FPS Franchise' },
  { word: 'Grand Theft Auto', clue: 'Open World Crime' },
  { word: 'Red Dead Redemption', clue: 'Western Cowboy Outlaw' },
  { word: 'The Last of Us', clue: 'Zombie Apocalypse Joel Ellie' },
  { word: 'God of War', clue: 'Kratos Norse Mythology' },
  { word: 'Uncharted', clue: 'Nathan Drake Treasure Hunter' },
  { word: 'Assassin\'s Creed', clue: 'Historical Parkour Assassin' },
  { word: 'The Witcher 3', clue: 'Geralt Monster Hunter' },
  { word: 'Cyberpunk 2077', clue: 'Futuristic Night City' },
  { word: 'Skyrim', clue: 'Elder Scrolls Dragon Born' },
  { word: 'Fallout', clue: 'Post Apocalyptic Wasteland' },
  { word: 'Halo', clue: 'Master Chief Spartan' },
  { word: 'Gears of War', clue: 'Cover Shooting Locust' },
  { word: 'Doom', clue: 'Demon Hell FPS' },
  { word: 'Overwatch', clue: 'Team Hero Shooter' },
  { word: 'Apex Legends', clue: 'Battle Royale Legends' },
  { word: 'Valorant', clue: 'Tactical 5v5 Shooter' },
  { word: 'Counter-Strike', clue: 'Bomb Defusal Terrorists' },
  { word: 'Rainbow Six Siege', clue: 'Tactical Breach Operators' },
  { word: 'Battlefield', clue: 'Large Scale War FPS' },
  { word: 'Destiny', clue: 'Sci Fi Looter Shooter' },
  { word: 'League of Legends', clue: 'MOBA 5v5 Champions' },
  { word: 'Dota 2', clue: 'MOBA Ancients Defense' },
  { word: 'Smite', clue: 'Third Person MOBA Gods' },
  { word: 'World of Warcraft', clue: 'MMORPG Azeroth' },
  { word: 'Final Fantasy XIV', clue: 'MMORPG Eorzea' },
  { word: 'Elder Scrolls Online', clue: 'MMORPG Tamriel' },
  { word: 'Rocket League', clue: 'Soccer with Cars' },
  { word: 'FIFA', clue: 'Soccer Sports Game' },
  { word: 'NBA 2K', clue: 'Basketball Sports Simulation' },
  { word: 'Madden NFL', clue: 'American Football Game' },
  { word: 'WWE 2K', clue: 'Wrestling Sports Entertainment' },
  { word: 'Mortal Kombat', clue: 'Brutal Fighting Fatalities' },
  { word: 'Street Fighter', clue: 'Hadouken Fighting Game' },
  { word: 'Tekken', clue: 'Iron Fist Tournament' },
  { word: 'Super Smash Bros', clue: 'Nintendo Crossover Fighting' },
  { word: 'Mario Kart', clue: 'Racing Karts Items' },
  { word: 'Super Mario', clue: 'Plumber Princess Rescue' },
  { word: 'The Legend of Zelda', clue: 'Link Triforce Hyrule' },
  { word: 'Pokémon', clue: 'Catch Train Battle Monsters' },
  { word: 'Animal Crossing', clue: 'Island Life Villagers' },
  { word: 'Splatoon', clue: 'Ink Shooting Squids' },
  { word: 'Kirby', clue: 'Pink Puffball Inhale' },
  { word: 'Metroid', clue: 'Samus Aran Bounty Hunter' },
  { word: 'Donkey Kong', clue: 'Barrel Throwing Ape' },
  { word: 'Sonic', clue: 'Blue Hedgehog Speed' },
  { word: 'Crash Bandicoot', clue: 'Spinning Marsupial' },
  { word: 'Spyro', clue: 'Purple Dragon Fire' },
  { word: 'Ratchet & Clank', clue: 'Lombax Robot Duo' },
  { word: 'Sly Cooper', clue: 'Thief Raccoon' },
  { word: 'Resident Evil', clue: 'Survival Horror Zombies' },
  { word: 'Silent Hill', clue: 'Psychological Horror Fog' },
  { word: 'Dead Space', clue: 'Space Horror Necromorphs' },
  { word: 'Outlast', clue: 'Asylum Horror Camera' },
  { word: 'Amnesia', clue: 'First Person Horror Sanity' },
  { word: 'Five Nights at Freddy\'s', clue: 'Animatronic Horror' },
  { word: 'Subnautica', clue: 'Underwater Alien Ocean' },
  { word: 'Terraria', clue: '2D Minecraft Bosses' },
  { word: 'Stardew Valley', clue: 'Farming Simulation Pixel' },
  { word: 'The Sims', clue: 'Life Simulation Game' },
  { word: 'Cities Skylines', clue: 'City Building Simulation' },
  { word: 'Civilization', clue: 'Turn Based Strategy Empire' },
  { word: 'Age of Empires', clue: 'RTS Historical Wololo' },
  { word: 'StarCraft', clue: 'RTS Space Zerg Protoss' },
  { word: 'Total War', clue: 'Grand Strategy Battles' },
  { word: 'XCOM', clue: 'Tactical Alien Defense' },
  { word: 'Portal', clue: 'Puzzle Physics Portals' },
  { word: 'Half-Life', clue: 'Gordon Freeman Crowbar' },
  { word: 'BioShock', clue: 'Underwater City Rapture' },
  { word: 'Dishonored', clue: 'Stealth Powers Revenge' },
  { word: 'Deus Ex', clue: 'Cyberpunk Stealth RPG' },
  { word: 'Metal Gear Solid', clue: 'Stealth Tactical Snake' },
  { word: 'Splinter Cell', clue: 'Sam Fisher Night Vision' },
  { word: 'Hitman', clue: 'Bald Assassin Agent 47' },
  { word: 'Dark Souls', clue: 'Difficult Die Repeat' },
  { word: 'Bloodborne', clue: 'Gothic Horror Hard' },
  { word: 'Elden Ring', clue: 'Open World FromSoftware' },
  { word: 'Sekiro', clue: 'Samurai Shinobi Prosthetic' },
  { word: 'Ghost of Tsushima', clue: 'Samurai Mongol Invasion' },
  { word: 'Horizon', clue: 'Robot Dinosaur Post Apocalyptic' },
  { word: 'Spider-Man', clue: 'Web Swinging Marvel' },
  { word: 'Batman Arkham', clue: 'Dark Knight Detective' },
  { word: 'Tomb Raider', clue: 'Lara Croft Archaeologist' },
  { word: 'Diablo', clue: 'Dungeon Crawler Loot' },
  { word: 'Path of Exile', clue: 'Action RPG Skill Tree' },
  { word: 'Warframe', clue: 'Space Ninja Looter' },
  { word: 'Monster Hunter', clue: 'Giant Creature Hunting' },
  { word: 'Dragon Age', clue: 'Fantasy RPG BioWare' },
  { word: 'Mass Effect', clue: 'Space RPG Commander Shepard' },
  { word: 'Fallout New Vegas', clue: 'Post Nuclear Vegas' },
];
