export interface WordPair {
  word: string;
  clue: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

export const youtubers: WordPair[] = [
  { word: 'MrBeast', clue: 'PewDiePie', difficulty: 'easy' },
  { word: 'Markiplier', clue: 'Jacksepticeye', difficulty: 'easy' },
  { word: 'Dream', clue: 'GeorgeNotFound', difficulty: 'easy' },
  { word: 'Ninja', clue: 'Tfue', difficulty: 'easy' },
  { word: 'Pokimane', clue: 'Valkyrae', difficulty: 'medium' },
  { word: 'Logan Paul', clue: 'Jake Paul', difficulty: 'easy' },
  { word: 'KSI', clue: 'Sidemen', difficulty: 'medium' },
  { word: 'SSSniperWolf', clue: 'AzzyLand', difficulty: 'medium' },
  { word: 'Dude Perfect', clue: 'Yes Theory', difficulty: 'medium' },
  { word: 'Ryan\'s World', clue: 'Kids Diana Show', difficulty: 'hard' },
  { word: 'Emma Chamberlain', clue: 'David Dobrik', difficulty: 'medium' },
  { word: 'James Charles', clue: 'Jeffree Star', difficulty: 'medium' },
  { word: 'Liza Koshy', clue: 'Lele Pons', difficulty: 'medium' },
  { word: 'Smosh', clue: 'Rhett and Link', difficulty: 'medium' },
  { word: 'Good Mythical Morning', clue: 'Epic Meal Time', difficulty: 'hard' },
  { word: 'VanossGaming', clue: 'H2ODelirious', difficulty: 'hard' },
  { word: 'Jenna Marbles', clue: 'Safiya Nygaard', difficulty: 'hard' },
  { word: 'Casey Neistat', clue: 'Peter McKinnon', difficulty: 'hard' },
  { word: 'Linus Tech Tips', clue: 'Marques Brownlee', difficulty: 'medium' },
  { word: 'MKBHD', clue: 'Unbox Therapy', difficulty: 'medium' },
  { word: 'Vsauce', clue: 'Veritasium', difficulty: 'hard' },
  { word: 'Kurzgesagt', clue: 'TED-Ed', difficulty: 'hard' },
  { word: 'PrestonPlayz', clue: 'Unspeakable', difficulty: 'hard' },
  { word: 'DanTDM', clue: 'Stampylonghead', difficulty: 'medium' },
  { word: 'Aphmau', clue: 'LDShadowLady', difficulty: 'hard' },
  { word: 'The Try Guys', clue: 'BuzzFeed Video', difficulty: 'medium' },
  { word: 'CollegeHumor', clue: 'Funny or Die', difficulty: 'hard' },
  { word: 'Philip DeFranco', clue: 'H3H3Productions', difficulty: 'hard' },
  { word: 'Shane Dawson', clue: 'Ryland Adams', difficulty: 'medium' },
  { word: 'Tana Mongeau', clue: 'Trisha Paytas', difficulty: 'hard' },
  { word: 'CallMeCarson', clue: 'Jschlatt', difficulty: 'hard' },
  { word: 'TommyInnit', clue: 'Tubbo', difficulty: 'medium' },
  { word: 'Wilbur Soot', clue: 'Technoblade', difficulty: 'hard' },
  { word: 'Corpse Husband', clue: 'Sykkuno', difficulty: 'medium' },
  { word: 'Ludwig', clue: 'xQc', difficulty: 'hard' },
  { word: 'Disguised Toast', clue: 'Scarra', difficulty: 'hard' },
  { word: 'Michael Reeves', clue: 'William Osman', difficulty: 'hard' },
  { word: 'Demolition Ranch', clue: 'Kentucky Ballistics', difficulty: 'hard' },
  { word: 'The Slow Mo Guys', clue: 'The King of Random', difficulty: 'medium' },
  { word: 'Mark Rober', clue: 'Stuff Made Here', difficulty: 'medium' },
  { word: 'Binging with Babish', clue: 'Joshua Weissman', difficulty: 'medium' },
  { word: 'Gordon Ramsay', clue: 'Jamie Oliver', difficulty: 'easy' },
  { word: 'Tasty', clue: 'Sorted Food', difficulty: 'hard' },
  { word: 'Yoga with Adriene', clue: 'Blogilates', difficulty: 'hard' },
  { word: 'FitnessBlender', clue: 'Chloe Ting', difficulty: 'hard' },
  { word: 'Jeffree Star', clue: 'NikkieTutorials', difficulty: 'medium' },
  { word: 'Bretman Rock', clue: 'Patrick Starrr', difficulty: 'hard' },
  { word: 'Jeffree Star Cosmetics', clue: 'Morphe', difficulty: 'hard' },
  { word: 'Roblox', clue: 'Flamingo', difficulty: 'medium' },
  { word: 'Game Theory', clue: 'Film Theory', difficulty: 'hard' },
];
